### ISSUE TITLE
2.1.14 - Name for style 17A is incorrect, should be British not English

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1010]
Version: 2.14

Installation URL:

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: The name of the Style for 17A in the 2015 guidelines is "British Strong Ale" not "English Strong Ale". BCOEM states the latter.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Doh! Over 3 years since BJCP 2015 styles were integrated and no one has caught this until now @jimmyorkin. You win!

A fix will be in the next version.

If it's really bugging anyone, you can run this SQL statement in your DB via phpMyAdmin or shell access. Replace `prefix_` with your install's prefix or delete it.
```
UPDATE `prefix_styles` SET brewStyle='British Strong Ale' WHERE brewStyle='English Strong Ale' AND brewStyleVersion='BJCP2015';
```
