### ISSUE TITLE
Private hosted site won't upgrade

### ISSUE THREAD

**Issue by brouse69** [geoffhumphrey/brewcompetitiononlineentry#1023]
Version: 
1.3.2.0

Installation URL: 
DCHBCompetition.com

Is your installation hosted on brewcompetition.com or brewcomp.com?
Np

Description of Issue:
We have an existing installation with version 1.3.2.0. Last year, I tried to update it to the latest version and it wouldn't update. I am trying again, and getting the same problem. If I specify "/update.php" on the URL, it responds with a page with a title of "BCOE&M 1.3.2.0 Database Update Script" and the message that the installed version is the same as the upgrade (which is version 2.1.14.0). I've tried everything I can, and nothing works. This is critical because now the Captcha no longer works. 

I would be willing to provide the FTP credentials for you to look at it.

**Comment by geoffhumphrey** [comment]
Hi @brouse69 - unfortunately, I'm not able to recreate the issue on any of my test environments due to the use of unsupported php mysql functions (and not mysqli that is now standard). 

My suggestion would be to not try and upgrade all the way to 2.1.14. Perhaps start with 2.0.0 and see if that works. If so, then try 2.1.0, then 2.1.14.
