### ISSUE TITLE
BCOE&M 2.1.12: Suspected SPAM received from brewdrinkrepeat.com

### ISSUE THREAD

**Issue by aliciad19363** [geoffhumphrey/brewcompetitiononlineentry#1050]
Version:
BUZZ OFF 25 – BCOE&M 2.1.12 Amateur Competition Edition 2009-2019

Installation URL:
http://brewdrinkrepeat.com/buzzoff

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:
Received an email from noreply@brewdrinkrepeat.com (name shown as "BUZZ OFF 25 Server") which appears to be SPAM. Image attached.

![Picture1](https://user-images.githubusercontent.com/49731931/56315774-98b28a80-6126-11e9-8b01-8296cb3d94aa.jpg)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @aliciad19363, thanks for reporting.

The scripting for the contact function creates an email whose originating address is a "noreply@"(domain name) instead of the user's email address who is trying to get in contact with you. 

BCOE&M does this to prevent some services, such as Gmail, from rejecting the email because the originating server's domain does not match the email address's domain name listed in the "From" header (this practice is commonly called "spoofing" and this is the most rudimentary way of going about that).

Gmail permitted the email to come to you because the originating domain of the email being sent (brewdrinkrepeat.com) was the same domain name of the email address in the "From" field in the header (noreply@brewdrinkrepeat.com).

You may or may not have a noreply@ email address on your server, but Gmail doesn't know that, nor does it care, really.

If the email header had any address that _wasn't_ from the brewdrinkrepeat.com domain, Gmail would have rejected it as a "spoofed" email.

This is why the address that the sender entered is listed in the body of the email. Note the text in the bottom of the email:

> Use [the above email address] if you try to reply and the email address contains "noreply" in it. Common with web-based mail services such as Gmail.

Anyway, it looks like someone from Russia is trying to tell you something. :) This type of SPAM is common, but not as common as the SPAMbots that are out there. BCOE&M attempts to mitigate bots by utilizing Google's reCAPTCHA v2, but sometimes things may get through - most likely by a motivated human. Obviously, I would strongly suggest trashing this email.

**Comment by aliciad19363** [comment]
Thank you so much for the quick and very helpful response!

**Comment by aliciad19363** [comment]
Hello Geoff,
I’m trying to log on to the BUZZ OFF website http://brewdrinkrepeat.com/buzzoff/ and I am getting a “site can’t be reached” error on my PC and “Safari cannot open the page because it could not connect to the server” on my phone. Are you able to tell what’s wrong?

**Comment by geoffhumphrey** [comment]
Usually connection issues are server-based (server is down, incorrect IP, etc.) and or end user-based (connectivity issues). In any case, it appears that the site is back up. I would check with your web host to see if there were any server outages yesterday.
