### ISSUE TITLE
2.1.17 - Site displays raw PHP code

### ISSUE THREAD

**Issue by FDillon00** [geoffhumphrey/brewcompetitiononlineentry#1052]
Version:2.1.17

Installation URL:https://lawrencebrewers.org/competition/

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue: htaccess file since version 2.1.15 causes site to display raw php. I had a issue with printing score sheet labels and as suggested upgraded from 2.1.14 to 2.1.17.  The reason I didn't do this is many previous issues one of which was the site displaying raw php.  
Upgrade issue discussed here: https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1045#issuecomment-474053895

So in order to get the labels a attempted another upgrade, highly risking as judging starts today, and got the raw php.  So I uploaded my old htaccess file and the site now renders correctly. 

commit: https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/79d68eb9f56147b525b560aea0c39eec5515beb0#diff-8052c42ab3b8aa06a3f5f788a4ddccc2

**Comment by graemecoates** [comment]
I see this as well after upgrade. The issue is at the bottom of .htaccess :

### php handler provided by phpupgrader ###
AddHandler application/x-httpd-ea-php70 .php

.htaccess should not be setting the php handler!! If the web server config permits it, this overrides the current handler, and breaks the site - this line needs to go from the general release code.

**Comment by graemecoates** [comment]
This is the commit it appeared to get added into:

https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/4f5efafd95107734e0537baba9348844e3f66731#diff-8052c42ab3b8aa06a3f5f788a4ddccc2

**Comment by FDillon00** [comment]
Thanks @graemecoates, this web stuff baffles me I'm happy to stick to C++ server code....
