### ISSUE TITLE
2.1.17 - BOS Winners Display setting should be separate from BOS Qualifying Entries setting

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1071]
**Version:** 2.1.17

**Installation URL:** seasonal.gtabrews.ca

**Is your installation hosted on brewcompetition.com or brewcomp.com?** Self Hosted

**Description of Issue:**

I've noticed that the setting used to determine how many BOS spots to show in the results is the same as the one used to determine how many of the winners from each flight are eligible for BOS contention.

This one:
![image](https://user-images.githubusercontent.com/1551339/59387185-89227d00-8d36-11e9-8c73-1aed18c064d6.png)

The result of this for my competitions is that I need to set this to "1" during judging, to ensure that BOS pullsheet and cup-mat only contain the 1st place entry from each table. Then after judging I need to change it to "1,2,3,HM" to ensure the winner display and reports contain all the BOS winners.

I would recommend renaming this setting to "BOS Qualifying Entries", then decouple it from the winner display function. Instead just have the winner display function show the places entered in "BOS Entries and Places". If a competition only wants to show 1st BOS, then they would only enter that 1st BOS in "BOS Entries and Places".

I think this would be much more intuitive than what we have now.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by ercousin** [comment]
@geoffhumphrey did you get a chance to look at this?

I've noticed a lot of competitions on our Canadian circuit have been hit by why, and only end up displaying 1st BOS.

**Comment by geoffhumphrey** [comment]
I did, Eric. Renaming is easy. However, disassociating the display code from the qualifying code is a deeper matter that, truthfully, I haven't had much time to tackle.

**Comment by geoffhumphrey** [comment]
See #1117.

**Comment by geoffhumphrey** [comment]
This will actually be in place for 2.2.0. The fix was pretty simple and did not involve any further DB changes; only a change to the /includes/db/output_results_download_bos.db.php file.

Essentially, the relationship will be severed. The BOS Method associated with the Style Type will only dictate which placing entries will be considered by the system for the BOS round and associated pullsheets (1st place only, 1st and 2nd, etc., etc.). The system will now display any and all "placing" BOS entries for each style type. Admins can designate up 1-3 and HM.

This fix is in the latest commit and will be in the next release.
