### ISSUE TITLE
Uploaded scoresheets not displaying gavel icon indicating downloads available

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#1077]
Version:  BCOE&M 2.1.17 

Installation URL: https://www.obw.brewcomp.com/

Installation hosted on brewcomp.com?

Description of Issue:

Scoresheets were uploaded to database as they were scanned during the competition. They appear to have correct filenames that include the six-digit entry number, yet they are not displaying the gavel icon indicating they are available for download.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
The names of the uploaded scoresheets (minus the .pdf extension) must match exactly the 6-digit Judging Number or Entry Number associated with the entry. In looking at your uploads, that doesn't seem to be the issue here though.

Via Site Preferences, you need to choose whether you are utilizing the Entry Number or Judging Number for scoresheet filename identification purposes. In your installation, the Judging Number option is chosen. I did a quick random sampling of your uploaded scoresheets and it appears that the PDF file names line up with Entry Numbers. If that's the case, it's simply a matter of going to Admin Dashboard > Preferences > Website and choosing "6-Digit Entry Number" for the _Scoresheet Upload File Names_ item.

**Comment by jodygrenert** [comment]
Thanks, Geoff. I made the change you suggested and now the PDFs are showing up as available for download. User error on my part.
