### ISSUE TITLE
Unable to edit competition info

### ISSUE THREAD

**Issue by GraintoGlass** [geoffhumphrey/brewcompetitiononlineentry#1078]
Version:
2019 Snake Saturday Irish Competition – BCOE&M 2.1.11 Amateur Competition Edition 2009-2019

Installation URL: I don't know.

Is your installation hosted on brewcompetition.com or brewcomp.com? I don't know.

Description of Issue:
After archiving, downloading, and purging previous data.  The message I receive:  Not Acceptable! An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

**Comment by geoffhumphrey** [comment]
This message seems to have to do with your web server or web host, who are utilizing Apache's mod_security tool. My advice would be to 1) update your installation to the latest BCOE&M version, 2.1.17 and to 2) read [this Stack Overflow post](https://stackoverflow.com/questions/28090737/not-acceptable-an-appropriate-representation-of-the-requested-resource-could-no) for possible solutions.

**Comment by geoffhumphrey** [comment]
This issue is caused by server environments employing a fairly strict Mod_Security protocol that rejects most HTML characters when posting data. By default, the competition info update function passes HTML characters, thus triggering the rather cryptic, unhelpful, and wholly annoying message.

With the latest commit and for the next release, there will be an option to utilize Markdown (a standard formatting methodology that posts data as plain text) instead of HTML for formatting text when updating competition information via Admin > Competition Preparation > Edit Competition Info.

To implement:

- Download the latest commit (if prior to the v2.1.18 release) or release.
- Open the /paths.php file and change the ENABLE_MARKDOWN definition to TRUE. Save the file.
- Upload/replace the updated files to your server.

Once implemented, instead of using the text editor you're used to, another one is in place that formats text you specify in Markdown, which is then passed as plain text for storage in the database.  The formatting you specify via the editor will be displayed as normal on  your installation's Info page and home page; it's just a bit of a different way of getting there as you'll note when you see it.

By and large, you should be able to use the provided text editor much like the previous one. You can make links and bulleted lists, as well as highlight and make text italic, bold, etc. as you're used to using the word processor-like interface. There is also a Preview button to allow you to see how your text with Markdown syntax will be displayed before you update.

Much more can be done with Markdown, however. There is a complete [Markdown tutorial](https://www.markdowntutorial.com/) as well as a [Markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for a quick reference of Markdown syntax, which, you'll probably note, it fairly simple.
