### ISSUE TITLE
Mid-word capitalization in entrant name is clobbered

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1102]
Version: 2.1.18
Installation URL: brewslam.gtabrews.ca
Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted
Description of Issue:

I'm seeing a strange bug. I have an entrant that complained BCOEM was changing capital letters in their last name to lower case. I tried it on my end and see the same thing...

What I enter on the form:
![image](https://user-images.githubusercontent.com/1551339/67917216-b9947780-fb6e-11e9-8ae9-aaed1795310b.png)

What shows up on the Participants page:
![image](https://user-images.githubusercontent.com/1551339/67917243-d335bf00-fb6e-11e9-98b2-2b514e2eec1e.png)

The strange thing is that I have other participants with capital letters in the middle of their last name, and it shows up fine in the database.

I suspected it had something to do with a difference on the "Account Creation" form vs "Account Edit" form, so I picked a lucky entrant:
![image](https://user-images.githubusercontent.com/1551339/67917362-20b22c00-fb6f-11e9-9c97-acbcdc89d4b6.png)

I was able to use the same form to edit his last name and add an extra y without affecting the uppercase C:
![image](https://user-images.githubusercontent.com/1551339/67917414-522af780-fb6f-11e9-97b2-9f8263f3c380.png)

I'm stumped...

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by ercousin** [comment]
I was able to edit it in the backend database directly:
![image](https://user-images.githubusercontent.com/1551339/67917709-44c23d00-fb70-11e9-9832-2d33dff7a85e.png)

**Comment by julien-gibson** [comment]
I've seen similar.  We have a surname Macey that gets turned into MacEy

**Comment by geoffhumphrey** [comment]
Whoops, missed this one way back when...

There's a function in /lib/process.lib.php called _standardize_name_ that all first names and last names entered are run through to standardize display of first names, last names, street names, etc.

For standardization, the function first sets the name to all lower-case, and then looks for some common "word splitters" in a name, such as a dash (-) or "Mc" to correctly capitalize the succeeding letter. 

This is why McCready is correctly capitalized, but Macey is not. The function looks only for splitters and since "Mac" is a splitter, MacEy is the output. Obviously the function isn't perfect, but it does work for the vast majority of Latin-character surnames

To prevent the weirdness, you could simply not call the function on lines 227-230 in the /includes/process/process_brewer_info.inc.php file. That would look like this:
```
$first_name = $purifier->purify($_POST['brewerFirstName']);
$last_name = $purifier->purify($_POST['brewerLastName']);
$address = $purifier->purify($_POST['brewerAddress']);
$city = $purifier->purify($_POST['brewerCity']);
```
This would allow users to put enter their names into the system in any way they wish - it still will be stripped of any code, etc, using the ``$purify`` function. The name will not be converted to mixed case - users can enter all capital letters (MCCREADY), or all lower-case letters (mccready), or any other combination thereof (mCCreAdy) and that's what will be displayed.

Otherwise, further customization of the _standardize_name_ function would be necessary to catch the issues you're experiencing. 

I'm exploring a more robust solution. Otherwise, I may just discontinue use of the function and trust users to not uglify their own names. :)

**Comment by ercousin** [comment]
Hi @geoffhumphrey 

I see you made a commit, does that mean we don't need to hack the file if we pick up the latest master commit?

**Comment by geoffhumphrey** [comment]
No need to hack, but please thoroughly test if you utilize the commit. It should be noted that this script only applies to Latin character-based languages.

After researching, I found [a class on GitHub](https://github.com/joshfraser/PHP-Name-Parser) from Josh Fraser that seeks to solve the problem that the original function attempted to address, but takes it a few step further. Essentially, it will allow for additions of prefixes, suffixes as well as account for names with "camelCase" (e.g., _MacAdoo_ and _DeMerchant_). In my testing, it worked quite well without clobbering a person's name. A person could enter _Dr joseph p DeHart III_ and the script will return _Dr. Joseph P._ as the first name and _DeHart III_ as the last name.

The new scripting is a happy medium - most people's names, which are uniquely their own, aren't messed with too much and some control of capitalization and mixed-case rules are still enforced - _JOHN_ will be converted to _John_, but _MACAVOY_ will not be converted to _MacAvoy_ -- it would be converted to _Mcavoy_. The idea that the user would see that and make an effort to fix it -- if they enter _MacAvoy_ the class will not convert it to _Macavoy_ and if they enter _Macavoy_, it will not convert it to _MacAvoy_ (the previous script would make that conversion).

Anyway, try it out if you'd like and post any issues you have. 

As with any scripting that attempts to "normalize" entry of people's names, there will be corner cases of when it won't work. For example, this script will convert _Erich von der Haghe_ to _Erich Von der Haghe_. I'm investigating ways around that.

**Comment by ercousin** [comment]
This sounds great to me!
