### ISSUE TITLE
"Porter" Truncated from "Pre-Prohibition Porter" Bottle Label

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#1120]
Version: 2.1.18
Installation URL: brewslam.gtabrews.ca
Is your installation hosted on brewcompetition.com or brewcomp.com? Self Hosted
Description of Issue:

Hi @geoffhumphrey ,

During Brew Slam 2019 I noticed several new bugs with the "With Required Info - All Styles (Judging Numbers)" stickers. It's possible they are all related to a single root cause, but I'm creating 3 issues because they appear to be independent to me.

Issue 2)
"Porter" Truncated from "Pre-Prohibition Porter" Bottle Label

Entry Info in Software:
![image](https://user-images.githubusercontent.com/1551339/69102056-51c7a300-0a2f-11ea-8e5b-651ca0ff315f.png)

Generated Bottle Label:
![image](https://user-images.githubusercontent.com/1551339/69102090-686dfa00-0a2f-11ea-95cc-ddf5e997d0aa.png)

This is made even more confusing when compared to the Pre-Prohibition Lager bottle label above it:
![image](https://user-images.githubusercontent.com/1551339/69102115-7e7bba80-0a2f-11ea-8f05-8a726dcdbeb6.png)

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Thanks for your report. A fix for this issue is in the latest master commit will be in the next release. _Pre-Prohibition_ has been abbreviated to _Pre-Prohib._ 

![image](https://user-images.githubusercontent.com/5216502/69664823-5b13c980-1046-11ea-8588-18faf539fe3f.png)

Additionally, other words have been abbreviated to allow for styles with longer names to be fully understood, yet still fit on the label. These will be their abbreviations:
* Mixed Ferm. Sour Beer
* Czech Prem. Pale Lager
* Aust. Sparkling Ale
* Spice/Herb/Veg Beer
* Spice/Herb/Veg Mead
* Cl. Style Smoked Beer
* Anything with "Specialty" in the title:
    - Spec. IPA
    - Wild Spec. Beer
    - Spec. Fruit Beer
    - Spec. Smoked Beer
    - Spec. Wood-Aged Beer
    - Spec. Cider/Perry

Download and replace the /output/labels.output.php file in your installation to implement.
