### ISSUE TITLE
2.1.18 - Entries Won't Get Marked As Paid

### ISSUE THREAD

**Issue by Fencer04** [geoffhumphrey/brewcompetitiononlineentry#1144]
Version: 2.1.18

Installation URL: https://limeadclassic.com/home

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:
The entries just won't get marked as paid. 

I have the PayPal information set up correctly and it's working for our other installation at https://limeadclassic.com/pro (using a different PayPal account). The setups for IPN and return URL are all correct but the one for /home just doesn't want to work. I have different IDs for each competition in their respective config files. 

Does anyone have anything I should look out for? I've set up a number of these installations and never had issues. This is the first one with two comps on the same domain so maybe it has something to do with that?

**Comment by geoffhumphrey** [comment]
It's my experience and understanding that PayPal's IPN will only work with one processing script per PayPal account. You mention using two different accounts, so this shouldn't be a problem - however, it's imperative that your PayPal accounts be business accounts to implement IPN. 

Beyond that, my advice would be to make sure to follow all setup procedures for [BCOE&M](https://brewcompetition.com/paypal-ipn) and [PayPal](https://developer.paypal.com/docs/ipn/integration-guide/IPNSetup/#id089EG030E5Z) and [test](https://developer.paypal.com/docs/ipn/integration-guide/IPNTesting/) using PayPal's [IPN simulator](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNSimulator/) and [sandbox](https://developer.paypal.com/docs/api/sandbox/sb-ipn/?mark=IPN#test-ipn-handling-in-the-sandbox) environment. 

The scripting in the ppv.php file was tested successfully in a variety of BCOE&M installation configurations, so my thought is that this is a PayPal configuration issue rather than a programmatic one.

**Comment by mpribble** [comment]
@Fencer04 I'm the organizer for [Colonial Cup ](https://colonialcup.lowcountrylibations.com/)in Charleston SC. We were literally having the exact same problem, but we were able to solve it...hopefully this comment from our registrar (he is running our BCOEM instance) might be relevant to you:

>Looks like it's fixed. The apache error log on the pine64 said it was missing a php function, which ended up being because it was missing a package. Installed php-curl and it worked after that. I just paid for an entry and after refreshing once it correctly showed as paid.

If you're running both competitions on the same host, then I suppose this wouldn't be relevant to you. But if they are different hosts, maybe check the one that's not working. I hope it helps.
