### ISSUE TITLE
Score Sheets not Matching Based on Judging Numbers in Database for Cider and Mead

### ISSUE THREAD

**Issue by bobwright011** [geoffhumphrey/brewcompetitiononlineentry#1145]
Version:2.1.17

Installation URL: GSHomebrewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: All of the score sheets upload correctly, but will not match in the database with any of the ciders or meads based on judging number.  The system was set assign judging numbers based on category and assigned them in the format of M2-001 or C1-001.  I also tried uploading them based on six digit entry number but this also didn't work.  All of the score sheets for beers uploaded flawlessly and all matched correctly.  Any ideas for how to solve this for ciders and meads?

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by bobwright011** [comment]
@geoffhumphrey - I actually solved the issue.  It seems the above problem stems from the judging number being assigned as Mx-xxx format and the matching function being case sensitive.  If I manually change the judging numbers to "mx-xxx" or cx-xxx" format, the matching works correctly.  Maybe something to consider in future upgrade cycle.

**Comment by geoffhumphrey** [comment]
@bobwright011 - after _finally_ checking into this issue today, I was racking my brain to figure out how mixed-case judging numbers were making it into the DB. I thought that I'd tracked down all entry points to convert any upper- and mixed-case entry of judging numbers to lower case (just for the reason you posted here about - providing access to scanned score sheets). Turns out I missed one.

I found that if a competition utilizes the QR code option to check in entries, mixed-case judging numbers would be allowed. I'm assuming that was the method you employed when checking in some or all of your received entries for the Garden State comp. If that's not the case, please let me know any and all methods you used to assign judging numbers to entries and I'll go back to the drawing board.

**Comment by bobwright011** [comment]
Geoff-
Thanks for the followup…I imagine that hunting down the bugs can be frustratingly tedious.  I didn’t use the QR code to check in the entries.  I did it all manually. After we closed the entry window, I regenerated the judging numbers using the "Judging Numbers (With Style Number Prefix)” option. 

Hope that helps…
Bob

**Comment by geoffhumphrey** [comment]
Thanks for the info, Bob. I'll continue to track down any and all entry points for generating judging numbers. The goal is to make sure that all judging "numbers" that employ alpha characters are converted to lowercase for use in the system and to match with any uploaded assets.
