### ISSUE TITLE
Enhancement - ability to remove Pro-Am question at registration

### ISSUE THREAD

**Issue by listening2tim** [geoffhumphrey/brewcompetitiononlineentry#1160]
Version:2.1.18

Installation URL:
https://competition.westcoastbrewers.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? NO

Description of Issue:
Anyone using the software outside of the us will probably not want to have the question  "Have you already been awarded a Pro-Am opportunity to compete in the upcoming Great American Beer Festival Pro-Am Competition?"  
Not a issue, just looks out of place for local clubs / State/ National competitions outside of US and the ability to remove would be great. Currently we just tell people to ignore.  

Thanks
  
Great product by the way - keep up the great work! Looking forward to seeing the AABC guidlines in the next version 👍 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @listening2tim - thanks for reporting. 

A fix for this is easy enough since the GABF Pro-Am is limited to the U.S. In the latest commit and in the next version, added scripting will dynamically show/hide Pro-Am indication field based upon the country chosen from the drop-down on registration pages and edit account pages. The Pro-Am field will show to users only if they chose United States.

The next version (2.1.19) with the AABC style guidelines is targeted for release on 24 July as testing is nearly completed.

**Comment by listening2tim** [comment]
Thanks Geoff for the prompt reply and update!  Appreciate your hard work! 

Cheers
Tim
