### ISSUE TITLE
2.1.19 Spammers sending mail using process_contacts.inc.php and reCAPTCHA enabled

### ISSUE THREAD

**Issue by cbwatkins** [geoffhumphrey/brewcompetitiononlineentry#1175]
Version: 2.1.19
Installation URL: https://competition.savannahbrewers.com/
Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: 
Spammers are sending mail using the process_contacts.inc.php file even though reCAPTCHA is enabled.  I originally posted the issue back in September 2020 and you concluded I was experiencing issue since reCATCHA was disabled.  You also stated "With reCAPTCHA enabled, you've eliminated the bots, but that won't stop a determined human from using the form to send spam if they care to take the time. These are very few and far between, however. I get a few from Russia every once in a while that are amusing."  

Is there a way to tell if the spam was sent by a bot or a human?  

We really need a way to stop the spammers.  If I cannot control it, then I will need to stop using BCOE&M, which pains me because it's an amazing application otherwise!  You have done excellent work, and we just need a security upgrade.

Thanks!

**Comment by prphntm63** [comment]
You can check the score of recatchpa requests on the [admin console](https://www.google.com/recaptcha/admin) which includes passed/failed requests.

**Comment by geoffhumphrey** [comment]
Hi @cbwatkins - I can certainly sympathize with you about spam and determined spammers; human and non-human alike. @prphntm63's suggestion for checking the reCAPTCHA admin console is a good first step and will tell you how many attempts were "Passed" (human) and "Failed" (non-human, most likely).

In the latest master commit, I've made some adjustments to the [contact.sec.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/sections/contact.sec.php) file to further address the issue. Once you've uploaded the new file to your server in the sections folder, you'll have two options:
1. Leave it as is. There is new coding to prevent end users from utilizing copy/paste. This **may** deter human spammers since they aren't able to paste their name, email, subject, and whatever they're hawking into the fields.
2. Delete all contacts via Admin > Competition Preparation > Manage Contact. This will replace the form with a message and will certainly stop any spam. You will need to replace the [en-US.lang.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/lang/en/en-US.lang.php) file in the /lang/en/ folder on your server if you go this route to display the default messaging.

If you do decide to take route 2, and you have another way for people to contact you at another website, you could utilize the Custom Modifications function to add a link to that form to your BCOE&M installation. I successfully tested this code to add a Contact Us link on the sidebar of all public pages, just replace YOURLINKHERE with the URL of that contact form:
```
<div class="panel panel-primary">
  <div class="panel-heading">
    <h4 class="panel-title">Contact Us</h4>
  </div>
  <div class="panel-body">
    <p>You can contact any competition official on <a href="YOURLINKHERE" target="_blank">at this website</a>.</p>
  </div>
</div>
```
Save the file with a .php extension (e.g., contact_us.php) and upload the file to the /mods/ directory of your BCOE&M extension. Then, go to Admin > Preferences/Customization > Custom Modules > Add. Make sure:
* Type is HTML
* Permission is set to All Users
* Display Order is set to Before Public Sidebar Content

After that, it should look similar to this:

![image](https://user-images.githubusercontent.com/5216502/97876051-8122fe80-1cd8-11eb-9fa6-2f4041fb6cf8.png)

**Comment by cbwatkins** [comment]
Geoff, I really appreciate your time in creating this fix!  BCOE&M is a phenomenal application.  Our brew club is very grateful for your work on this!  I'll monitor over time and let you know if this stops our spammer problem.

**Comment by cbwatkins** [comment]
Geoff, I don't believe I have seen any spammers use our site since I uploaded the latest contact.sec.php file, however the contact page doesn't work anymore.  Instead of showing a contact form, it shows the GitHub page for the conctact.sec.php file.

I attached a picture for archive, but you can checkout live site link as it current sits:
https://competition.savannahbrewers.com/contact

![2020-11-21_7-35-56 Contact Page Error](https://user-images.githubusercontent.com/35432328/99877444-5556b280-2bcc-11eb-86ad-3b38e6333675.jpg)

Can you help me get the contact form back without losing your latest fix in the file?

Thanks again for all your help!

**Comment by FDillon00** [comment]
I have had reCaptcha always enabled. The spam is bypassing it. I have a series of attempts on  11/11/2020.
![screenshot1](https://user-images.githubusercontent.com/5970995/102249735-4bbd2380-3ec8-11eb-92f8-ff6f346aa492.png)

Yet a steady increase in this same spam email that seems to be using hijacked email accounts that are simply quoting some text book. 
![screenshot](https://user-images.githubusercontent.com/5970995/102249866-6f806980-3ec8-11eb-9018-e9887822c214.png)


My version  2.1.17
URL: https://lawrencebrewers.org/competition
I disabled the contact page yesterday in the Website Preferences menu yesterday. When I get time, I'll upgrade and do the manual removal process.

**Comment by graemecoates** [comment]
The issue here is not so much that they are spamming the competition
contacts, but instead are using the feature that cc's in the entered email
address to perform a reflective spam against a completely innocent
recipient.

I raised this as an enhancement to turn this off, but have received no
reply.

Graeme

**Comment by geoffhumphrey** [comment]
@graemecoates, your issue (#1171) does make sense as a potential source of reflective spam and will be addressed in the next release and in an upcoming master commit.

Unfortunately, we're never going to be able to stop SPAM 100% of the time, especially if it's coming from an actual human. If they're determined enough, they'll get through.

**Comment by geoffhumphrey** [comment]
> 
> 
> Geoff, I don't believe I have seen any spammers use our site since I uploaded the latest contact.sec.php file, however the contact page doesn't work anymore. Instead of showing a contact form, it shows the GitHub page for the conctact.sec.php file.
> 
> I attached a picture for archive, but you can checkout live site link as it current sits:
> https://competition.savannahbrewers.com/contact
> 
> ![2020-11-21_7-35-56 Contact Page Error](https://user-images.githubusercontent.com/35432328/99877444-5556b280-2bcc-11eb-86ad-3b38e6333675.jpg)
> 
> Can you help me get the contact form back without losing your latest fix in the file?
> 
> Thanks again for all your help!

@cbwatkins, you're actually including the github page on your site - and I'm not entire sure how you did it. Instead, you'll need to actually download the code for the contact.sec.php (or copy and paste it) into your _local_ contact.sec.php file and then upload via FTP that file to your BCOE&M installation's /sections/ directory.
