### ISSUE TITLE
v2.1.19 - ALL Extra Required Info fields show for all styles if any styles require it - even if not needed

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1191]
Version: v2.1.19

Installation URL: https://bataille.deadyeast.org

Is your installation hosted on brewcompetition.com or brewcomp.com? no

Description of Issue:

Our comp this Saturday has several styles requiring extra info, in particular 21B (all) and Mead (all). However, when creating an entry and selecting a style that does not need this info, the extra required info fields and radio buttons are visible and available.

In addition, **all** possible fields regardless of entry type (beer or mead for example) are shown on the entry form and appear quite confusing with no designation as which one is actually required or to be used. There are 2 sets of radio buttons for each of Carbonation, Sweetness, and Color, and 3 for Strength, that reflect different types of entries.

Finally, all styles show the 'Required Info' text box with no indication (as a comment, or starter text like the Optional Info box) as to what should be typed in.

*Note, I do show a style in the first screenshot that requires special info, but all of these fields appear right at first, and none go away if you select a style that does not require them.

Expected Behavior:

Only those specifications required are shown and only those appropriate for the type of entry. Barring this, using the 'card suit' identifiers as part of the label for each radio option list would help. Copying the text from the style definition for the 'Required Info' box as hint/starter text would also be **very** helpful.

![Blank Required Info Box](https://user-images.githubusercontent.com/19876193/105811881-e18da900-5f72-11eb-94d0-efac66c79bd5.png)
![All option lists showing](https://user-images.githubusercontent.com/19876193/105812747-56adae00-5f74-11eb-8238-716a924ede8a.png)

**Comment by geoffhumphrey** [comment]
Hi @AdrienM76. Thanks for reporting. Unfortunately, after many varied attempts, I'm not able to re-create this in any of my test environments. Since the show/hide functionality depends upon jQuery, make sure javascript is enabled for the browser. 

My suggestion is to disable any addons that may interfere with javascript encoding as well as make sure you have javascript enabled for your browser. 

If the issue still persists, please do the following so I can attempt to diagnose it:

1. Access the Developer Tools for your browser.
   - Ctrl + Shift + I in Edge or Chrome.
   - Ctrl + Shift + K in Firefox.
   - Option + Command + I in Safari on Mac (you may need to [enable them](https://coolestguidesontheplanet.com/safari-web-developer-tools-show-dock-browser-window/) first).
2. View the Console.
3. Expand any errors you see.
4. Screenshot or copy/paste them and reply back here.

**Comment by AdrienM76** [comment]
JS is enabled. I had several entrants comment that they were confused by the options showing up when they weren't required for a style. And I had several entrants select something (some mead instead of beer related) because they thought they had to even when they did not.

I opened the console (Safari, but will be happy to test others) and attempted to edit two entries, one with special requirements (21B2: Black IPA) , and one without. (11C: Special Bitter)

As you can see from the screenshots, everything displays for both beers. (including mead options) And the console shows identical errors, save that the 11C triggered syntax error one line earlier.

![Screen Shot JS Console Safari - Black IPA](https://user-images.githubusercontent.com/19876193/106941255-33a79a80-66e8-11eb-8d66-e398dd456155.png)


![Screen Shot JS Console Safari - Special Bitter](https://user-images.githubusercontent.com/19876193/106941264-37d3b800-66e8-11eb-943d-02fdcd27bef4.png)

**Comment by AdrienM76** [comment]
I also tested on a clean Firefox 85 install, same results, and what look to be the same errors. (the FF console displays a bit differently)

I tested on a clean Vivaldi install with the same results. (didn't inspect the Console on that one)

These were done on MacOS Catalina, but I can test any other browser or OS if you need. I can't seem to get the options to *not* always appear.

**Comment by geoffhumphrey** [comment]
With those results, I'm kind of baffled. It could be environment-dependent. If you wouldn't mind, so I can inspect on your installation, would it be possible to create an administration account for me in your installation? Use prost [at] brewcompetition.com as the user name and then send the login credentials to that address (I'll make sure to change the password after logging in). This way I can get a feel for exactly what's happening.

**Comment by AdrienM76** [comment]
Done. Thanks.

**Comment by geoffhumphrey** [comment]
@AdrienM76, I believe I've found the issue. For your custom style (35-A Custom IPA) you defined some Entry Info text that had some double-quotes in the description:
> Specify either two or more existing BJCP styles, such as **"Red Rye IPA" or "Munich IPA"** and the beer will be judged using both style guidelines, otherwise specify an entirely custom name, such as **"Gulf Coast IPA"** and fill out the Description section. If you wish to specify hop variety or other ingredients, do so here. You may also enter a different strength version of a different BJCP IPA (e.g., session-strength American or English IPA) *Fruit, Spice, Vegetable, Smoked, or Wood Aged beers are NOT allowed*

Unfortunately, these double quotes were tripping up the javascript (it doesn't like double-quotes within double-quotes). In my own test environment, I was able to recreate the issue. When I removed the double-quotes from the custom style's Entry Info, the issue was resolved.

For the next version, I'll make sure to add filtering to convert any double- and single-quotes to their respective HTML entities for use in the system. When properly filtered, things run as expected.

**Comment by AdrienM76** [comment]
Awesome! Thanks for spending the time to track that down. That light bulb should have gone off for me since I'm the one who made the edit.

Do you still need that account or can I zap it?

**Comment by geoffhumphrey** [comment]
You can zap it if you'd like. Or demote me just in case another issue crops up. :)

**Comment by AdrienM76** [comment]
Ha, yeah, I have a habit of stumbling over bugs. Thanks again for your time and effort!
