### ISSUE TITLE
2.2.0 website prefs Styleset has no options, saves NULL to db

### ISSUE THREAD

**Issue by quimnut** [geoffhumphrey/brewcompetitiononlineentry#1202]
Version:
2.2.0 w/ baseline database

Installation URL:
https://uat.brisbanebrewersclub.com.au/

Is your installation hosted on brewcompetition.com or brewcomp.com?
no, as above

Description of Issue:
Styleset has no options in website preferences on baseline database, saves NULL to db.

**Comment by quimnut** [comment]
Adding
require_once (INCLUDES.'styles.inc.php');
to /var/www/html/includes/db/common.db.php 

makes them appear.

my error log was

[Wed Mar 17 13:30:43.969779 2021] [php7:notice] [pid 495] [client 172.18.0.2:58864] PHP Notice:  Undefined variable: style_sets in /var/www/html/includes/db/common.db.php on line 90
[Wed Mar 17 13:30:43.969807 2021] [php7:warn] [pid 495] [client 172.18.0.2:58864] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/includes/db/common.db.php on line 90
[Wed Mar 17 13:30:43.974217 2021] [php7:notice] [pid 495] [client 172.18.0.2:58864] PHP Notice:  Undefined index: style_set_beer_end in /var/www/html/includes/constants.inc.php on line 2582
[Wed Mar 17 13:30:43.974238 2021] [php7:notice] [pid 495] [client 172.18.0.2:58864] PHP Notice:  Undefined index: style_set_mead in /var/www/html/includes/constants.inc.php on line 2583
[Wed Mar 17 13:30:43.974242 2021] [php7:notice] [pid 495] [client 172.18.0.2:58864] PHP Notice:  Undefined index: style_set_cider in /var/www/html/includes/constants.inc.php on line 2584
[Wed Mar 17 13:30:43.974245 2021] [php7:notice] [pid 495] [client 172.18.0.2:58864] PHP Notice:  Undefined index: style_set_category_end in /var/www/html/includes/constants.inc.php on line 2585

**Comment by geoffhumphrey** [comment]
Hi @quimnut, thanks for reporting. Unfortunately, I couldn't replicate this issue on any of my test servers. 

The include you mention in your proposed fix will not hurt if you add it to the /includes/db/common.db.php file since it merely defines the `$style_sets` variable. However, in the base code for the 2.2.0 release, the /includes/styles.inc.php file is already called as an include on line 134 in the /site/bootstrap.php file (which, in turn, is called every time index.php is loaded) . So, I'm not sure why it didn't load on your server unless your bootstrap.php file wasn't updated to [the one included in the 2.2.0 release](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/v2.2.0/site/bootstrap.php). Perhaps that was the issue? If not, we can try to dive deeper.

**Comment by quimnut** [comment]
Ahhh, as it's living with config.php in site/ I have that path linked into my container, as files are immutable in containers and we edit config files.

Nice one, thanks.
