### ISSUE TITLE
25B Saison Shows Wrong Info

### ISSUE THREAD

**Issue by ramseybrews** [geoffhumphrey/brewcompetitiononlineentry#1209]
Version: BCOE&M 2.2.0

Installation URL: https://usopen.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp.com

Description of Issue: When you go to add an entry and select 25B Saison, it shows the information for the Historical Beer styles.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @ramseybrews, thanks for reporting. Confirmed - the wrong text string is being referenced by the jQuery statement. For non-hosted installations, it's a relatively simple fix. Swap line 26 in /includes/form_js.inc.php:
```
"25-B" => $styles_entry_text_27A,
```
With:
```
"25-B" => $styles_entry_text_25B,
```
The fix is in the latest master commit and will be in the next release.
