### ISSUE TITLE
Version 2.2.0 - Sponsor Levels

### ISSUE THREAD

**Issue by konevik** [geoffhumphrey/brewcompetitiononlineentry#1214]
Version: 2.2.0

Installation URL: https://doggdayzz.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? yes

Description of Issue:
I am having difficulty finding how to order/rank the sponsors. Our competition has different levels of sponsors (platinum, gold, silver, etc) depending on how much they donate. As I add sponsors and logos they display simply in the order I added them rather than by sponsor level. Is there a way to re-order the sponsors once added/uploaded? Is there a way to utilize the sponsor level feature that I am missing? 

Also, is there a way to only show level 1 sponsors on the home page and all sponsors (ordered as above) on the sponsor page? 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @konevik. Thanks for reporting. 

Indeed, admins can rank a sponsor from 1-5 and it stands to reason that they should be ordered by sponsor level (1 being the best) and then by name in alphabetical order when displayed on the Sponsors page. For some reason, that is not the case - it's been years the sponsors functions were created and I can't for the life of me think of a reason why I neglected to add any ordering to the MySQL query. 

Anyway, since you're hosted, I've corrected that in your installation.

The fix will be in the next version and in the latest master commit.

**Comment by konevik** [comment]
Fantastic, thank you!
kevin

**Comment by geoffhumphrey** [comment]
@konevik - you're welcome!

I forgot to answer the second question in your post.

> Also, is there a way to only show level 1 sponsors on the home page?

This would be possible with some custom php/html coding and the use of the custom modules function. Unfortunately, that function not available for hosted installations.
