### ISSUE TITLE
Lost my administrative permissions

### ISSUE THREAD

**Issue by JoeCMI** [geoffhumphrey/brewcompetitiononlineentry#1224]
Version:

Installation URL:https://maltinfusers.brewcompetition.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?
Brewcompetition.com

Description of Issue:
I am an administrator and I have lost my administrative permissions and cannot make any changes.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @JoeCMI - since you're not the contact person I have on record for that installation, please DM me here on GitHub or email me via the [brewcompetition.com/contact](https://brewcompetition.com/contact) page the following information - *as it appears in the BCOEM installation* - to verify your identity:
- First Name
- Last Name
- Email Address
- Phone Number
- Secret Question
- Secret Question Answer

**Comment by JoeCMI** [comment]
Hi Geoff,

 

My info is as follows:

Joe

Kulesa

***@***.***

513-543-8408

Who is my favorite group

Jimi Hendrix

 

Thanks in advance for reinstating my administrative permissions.

 

Joe Kulesa

**Comment by geoffhumphrey** [comment]
Hi Joe - I reached out to Tim McKee and he said you have taken over competition activities for the club. I've reinstated your Admin role as of this morning.

When replying to the email asking to verify your information, it was also posted to the issue string on GitHub. I've since removed that post, but I since it contained the answer to your secret question, I have removed the answer from your profile on the BCOEM installation for security reasons. When you log back in to the competition site, please make sure to update your account with a **different** secret question and answer combination.
