### ISSUE TITLE
ENHANCEMENT: Drop-Off Location Should Be Mandatory Information

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#1234]
When people are inputting their entries into the system, they should know which location they will be dropping off at (if they're not shipping).

This information should be **mandatory**. 

Context: I am currently running a 200-entry, three-bottle-per-entry competition. The database includes dropoff information for eight (8) entries out of 200.  :(

**Comment by geoffhumphrey** [comment]
Hi @BrewDrinkRepeat -- in a sense, the field is already mandatory since the user must chose something in the drop-down. Making the field required in the UI will probably not provide the information you're looking for, however, since "Not Applicable / Shipping Entries" is one of the responses. 

The solution to your predicament may be as simple as to change the UI to feature all drop-off locations before the "Not Applicable / Shipping Entries" choice. I'll do that in the next version; it'll look something like this:

![image](https://user-images.githubusercontent.com/5216502/133297647-d38ae048-9d9e-4f60-b2c4-cf424d0d9fcf.png)

We humans are a lazy lot if given the opportunity. :)
