### ISSUE TITLE
[2.3.0]PayPal IPN Not Working

### ISSUE THREAD

**Issue by Fencer04** [geoffhumphrey/brewcompetitiononlineentry#1238]
Version: 2.3.0

Installation URL: https://libme.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp.com

Description of Issue: PayPal IPN not working. I have the correct address set up on PayPal and it's enabled. I've also set up the return address as what is shown in the admin. This has worked in years past but doesn't seem to be now. Can this be looked at and resolved?

**Comment by geoffhumphrey** [comment]
Hi @Fencer04 - I've looked into the logs and at the payment records and they indicate: _Receiver Email Mismatch - Check PayPal Payment Email Address in Preferences_ - did the PayPal email address change? If not, we'll have to investigate other potential causes. The coding that processes the PayPal IPNs has not changed in any impactful way since December 2020.

**Comment by Fencer04** [comment]
@geoffhumphrey I noticed that the primary email address has changed. I updated that and will see if that resolves the issue. Once someone tries to pay again I'll update the ticket.

**Comment by Fencer04** [comment]
Once I had the primary email address on the account set correctly the issue was resolved.
