### ISSUE TITLE
Error: "unknown column 'judgingTime' in 'judging_locations'" after 2.3.1 upgrade

### ISSUE THREAD

**Issue by graemecoates** [geoffhumphrey/brewcompetitiononlineentry#1240]
Version:
2.3.1

Installation URL:
https://competitions.londonamateurbrewers.co.uk/lagerthanlife/

Is your installation hosted on brewcompetition.com or brewcomp.com?
NO

Description of Issue:
This was an old v2.1.18 install that has been upgraded to 2.3.1. There was already a completed competition after upgrade.

On attempting to login the following error (on white screen) was displayed:

`unknown column 'judgingTime' in 'judging_locations'`

This required setting of the FORCE_UPGRADE flag to resolve - looks like the auto upgrade function isn't handling this issue.

**Comment by geoffhumphrey** [comment]
In my test environment he cause for this error stemmed from accessing the BCOE&M installation via the browser with the 2.1.18 codebase installed on the server (which creates a new session), then updating the server files to 2.3.1, then accessing or refreshing the browser page. The presence of the session with the old codebase was prevented the update scripts from running. The next version will include scripting to reset the current session to address this situation. 

In the meantime, users who are upgrading should:
- Log out of any current sessions that use the old codebase.
- Quit their browser. Relaunch.
- Clear browser cache and cookies.
- Upload the 2.3.1 codebase to their server.
- Access the installation via the browser.

If that does not work, then the fallback @graemecoates mentions above will work:
- Open the /paths.php file in the text editor of your choice.
- Change the FORCE_UPDATE flag to TRUE -- the line should read ``define('FORCE_UPDATE', TRUE);``
- Upload (replace) the paths.php file in the root of the BCOE&M directory on the server
- Access or refresh the browser
- Change the FORCE_UPDATE flag back to FALSE and re-upload the file to the server

_Do not leave the FORCE_UPDATE flag as TRUE since the update scripts will run EACH time a page is accessed or refreshed_
