### ISSUE TITLE
2.3.1 - Login expiration causes the Score saving function to fail

### ISSUE THREAD

**Issue by grmelacz** [geoffhumphrey/brewcompetitiononlineentry#1259]
Version: 2.3.1

Installation URL: https://soutez.mhmeeting.cz

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When I log in, put my computer to sleep and open it again once my login cookie has expired, the request to save the score goes through and then fails (it's displayed correctly along the input field). I would expect it to force me to reload the page before entering more scores (someone may not notice it failed) or at least disable the field so I cannot enter any text until I log in again.

Side note: The login cookie is super short-lived anyway, I'd suggest to extend the expiration at least to one day, if it's not something you'd better not do (for any reason). Especially when the competition on, I have to re-login at least 5 times through the day.

**Comment by geoffhumphrey** [comment]
Hi @grmelacz, thanks for reporting. A way around this is to extend the login expiration for your installation to something like 1440 (a full day in minutes) in your /site/config.php file. Simply change the ``$session_expire_after`` variable to 1440 (or whatever you'd like) and re-upload to your installation. Logout, quit your browser, clear cache, and then log back in. 

To have the logout timer in the My Account dropdown read correctly for anything above 60 minutes, I had to make some adjustments to the /js_includes/autologout.min.js file. Available now in commit a6f337c1. Replace it on your server and your display should look like this (this example has the expiration set to 2160 minutes or 1.5 days):

![image](https://user-images.githubusercontent.com/5216502/144938866-2f8afc72-1f4f-4e1b-b254-6044b493de93.png)

** Please note that the logout warnings at 2 minutes and 30 seconds prior to your session's end will not show if the browser tab/window is not active. This is a browser setting and not a BCOE&M setting since monitoring of the DOM takes considerable resources that may affect performance.

**Comment by grmelacz** [comment]
Hey @geoffhumphrey, thanks for the quick solution & fix. Your help is much appreciated!
