### ISSUE TITLE
2.3.2 Archive function results in "Table 'brewcompetitiononlineentry.evaluation' doesn't exist" error

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1264]
Version: 2.3.2

Installation URL: https://register.worldcupofbeer.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? : No

Description of Issue:

Continuation of #1241 

In #1241 @graemecoates reports this issue for version 2.3.1. It appears that it's then fixed in 2.3.2 as Geoff marked as part of the [2.3.2 milestone](https://github.com/geoffhumphrey/brewcompetitiononlineentry/milestone/26)

I'm running 2.3.2. We have no `evaluation` table in our database from last year's competition. When I visit the URL

https://example.com/includes/process.inc.php?action=archive&go=add

I get the error

> `Table 'brewcompetitiononlineentry.evaluation' doesn't exist`

Some tables have been archived and some haven't. The `users` table is empty and so I had to restore from backup. In the end we worked around this by just not using the archive feature and purging everything instead.

I've read through the diff for 2.3.1 to 2.3.2 but can't find where this was fixed (this may just be because I'm not familiar enough with the code)

Was this fixed in 2.3.2 and I'm encountering a different problem? Did the fix in 2.3.2 not work?

**Comment by geoffhumphrey** [comment]
Hi @gene1wood, thanks for reporting.

After a cursory look at the code, lines 25-27 in the /includes/process/[proceess_archive.inc.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/includes/process/process_archive.inc.php) reference a function that checks whether the evaluation table exists when processing the archive request. However, I believe the issue lies with line 114, where the evaluation table is added to the array of tables that will be truncated.

The issue should be alleviated if line 114 is simply removed or commented out:
```
// if (!isset($_POST['keepEvaluations'])) $truncate_tables_array[] = $prefix."evaluation";
```

I haven't tested this as yet, but in looking at the code, this is what stands out to me. The $_POST['keepEvaluations'] variable referenced in that line does not exist when the Archive form is submitted, thus why it that line is being executed.
