### ISSUE TITLE
v2.3.2 What are the conditions needed for the "Register" button to not be disabled?

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#1278]
Version: 2.3.2

Installation URL: https://register.worldcupofbeer.com/index.php?section=register&go=judge

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue:

I'm trying to troubleshoot why it is that nobody can register. When I go to [our registration page](https://register.worldcupofbeer.com/index.php?section=register&go=judge), to begin with the "Register" button has the class `disable` which shows a circle with a line through it and colors the button a light blue implying it can't be clicked.

As I go through and fill out information, including clicking the Recaptcha, I keep hoping that one of those fields being filled out will satisfy the requirements for the Register button to be come un-disabled, but I haven't managed to figure it out.

# Question 1

Where is the frontend code that changes the class on that button so it's not disabled? From there I should be able to see what condition is causing registration to not work.

# Question 2

Is there any place to view or modify the unminified frontend javascript? I see all the minified versions here : https://github.com/geoffhumphrey/brewcompetitiononlineentry/tree/master/js_includes but where is the source js for this, that one would modify and then minify into a commit? For example commit 775b1fc30e1605c49b01b07b3ccd342732ca53ad shows a change to a minified js file but the unminified version isn't in the commit. Does this mean when you make a change to the frontend javascript you're actually editing minified code in it's minified form?

# Question 3

Why, if you click the button once, nothing happens, but if you double click the button a "Working please stand by" overlay appears?

**Comment by gene1wood** [comment]
So I think there are two problems that I'm seeing, that I think are unrelated.

The one I'm not worried about is that it looks like you can trigger the "loader" screen by double clicking a submit button and then single clicking it.

The more important problem which I'm trying to diagnose is that nobody can register (and our comp is live and open for registration so we're getting emails from folks saying that they can't register)

Here's a video of what users see when they try to register

[![Unable to Register](http://img.youtube.com/vi/rxVudavS7f0/0.jpg)](http://www.youtube.com/watch?v=rxVudavS7f0 "Unable to Register")

I've looked in the code of [`register.sec.php`](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/sections/register.sec.php) and I've read through the javascript and searched through the codebase for the string `disabled` to see what it could be that triggers the toggling of the "Register" button from the class of `disabled`. I'm just not seeing it.

Any guidance would be super appreciated.

**Comment by graemecoates** [comment]
You have to answer yes/no to every one of the stewarding session options - then "Register" will be enabled. It isn't obvious that those are mandatory fields...

**Comment by graemecoates** [comment]
@geoffhumphrey These fields are missing the "required" attribute. I feel that some additional visual guidance would be helpful across all the fields where the input is a required field.

**Comment by geoffhumphrey** [comment]
HI @gene1wood - in the video above, there were two items that were not completed that prevented submission of the form: the state (since you chose the US) and the drop-off location choice. I was able to register for the World Cup of Beer when all both of those were completed and when I responded "Yes" or "No" to all of the judging sessions - [demonstrated in this video](https://drive.google.com/file/d/1tRKETghNyt6bvFUboTk7D7FYypgYJdiQ/view).

Your frustration is understandable here. I'll work on making sure that all required items are clearly indicated as such in the UI for an upcoming version. In the meantime, I'm happy to look through and provide you an updated register.sec.php file that indicates all required fields with red text (or similar).

**Comment by gene1wood** [comment]
@geoffhumphrey Aha, ok cool.

> the state (since you chose the US) 

Actually I do set the state at 1:06 in the video

> the drop-off location choice

This is the problem.

Stewards and judges don't have a drop off location choice, they're not registering to enter beers, they're registering to volunteer (which doesn't involve dropping off beer)

This is the cause of the problem though. I've never filled out drop-off location (because stewards/judges don't have one) and I suspect judges/stewards also aren't. I'm surprised we haven't encountered this in years past using BCOE&M

Is it possible, just for the time being, to point me (link) to where in the code the check for these required fields is done that enables the register button? (So I can tweak it for the moment to not require drop off location)

**Comment by geoffhumphrey** [comment]
> Is it possible, just for the time being, to point me (link) to where in the code the check for these required fields is done that enables the register button? (So I can tweak it for the moment to not require drop off location)

The most direct way to do this is to remove _required_ from the select form element [at line 701 in the register.sec.php file](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/347b7bb56c6d51643260796c1b52c3dfc06a892a/sections/register.sec.php#L701).

That should get you up and running.

**Comment by jimmyorkin** [comment]
I discovered that setting the Judging Session is different if you go in registering as an entrant vs a judge. As an entrant, All the session answers were set to "no". Registering for just a Judge, All the choices were set to "select below". I think defaulting sessions to "no" is good. Forcing the judge registration to set all the sessions is cumbersome when we have 43 sessions.

**Comment by geoffhumphrey** [comment]
> As an entrant, All the session answers were set to "no". 

To clarify, entrants don't have these options, **upon registration**. After registration, if an entrant edits their account and indicates they are willing to judge and/or steward, their session availabilities do default to "No" since they first registered as a entrant only.

I guess it boils down to what your particular comp requires. I've had requests for the default to be "no" for instances like yours, Jimmy. But I've also had requests for it to be "yes" for the exact same reason. Finally settled upon the requirement to provide an answer for each, one way or another, so that comp directors/judge coordinators aren't assigning judges to flights in sessions they aren't really available for (or the opposite).

It's a hard nut to crack since comps that are using the package vary in size from very small, like one of my local ones (less than 100 entries), to very large, like Jimmy's (over 1000 entries).

**Comment by gene1wood** [comment]
@geoffhumphrey Thanks very much for the guidance! I made the change you suggested and indeed, now judges and stewards can register without asserting a beer dropoff location.

It looks like the logic in regards to the drop off location is

https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/e196fb640c2ffe0d8b1c92b71facc445186952e3/sections/register.sec.php#L696-L710

* If the competition is amateur, then show the beer drop off location selector to entrants, judges and stewards
* If the competition is professional, then only show the beer drop off location to entrants, not to stewards and judges

A not-urgent question : What's the rationale behind this distinction? What's the use case where an amateur competition would want to require beer drop off locations for judges and stewards?

**Comment by geoffhumphrey** [comment]
> If the competition is professional, then only show the beer drop off location to entrants, not to stewards and judges

This is the case now. Judges and entrants are separate entities. Judges are registered as individuals, entrants are registered as organizations.

> What's the rationale behind this distinction? What's the use case where an amateur competition would want judges and stewards to assert a beer drop off location (despite the fact that they're not entering beer, they're judging or stewarding)?

In an amateur competition, many judges and stewards are _also_ entrants - at least in my experience.  Often, calls for judges come before calls for entries, so a comp coordinator could open up registration for judges before general entrants. Since participants only create one account in the system, the judges who sign up early indicate their drop-off at registration to save a step later.

**Comment by gene1wood** [comment]
I'll close this out as my question is answered. It may make sense to open a new issue or PR to make this behavior selectable. For the time being I'll try overriding it with a "custom module"
