### ISSUE TITLE
Truncated incorrect DOUBLE value: 'default'

### ISSUE THREAD

**Issue by robdontay** [geoffhumphrey/brewcompetitiononlineentry#1301]
Version:2.4

Installation URL: abc.ehg.ca

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: When adding a new brewer/user/etc. I'm getting the following error.
Truncated incorrect DOUBLE value: 'default'

We are running this off a mysql 8 db on wordpress.

I had this issue doing the initial install so I went with the baseline install however now getting when trying to register.

Rob

**Comment by geoffhumphrey** [comment]
Hi @robdontay, thanks for reporting. At present, the application isn't fully compatible with MySQL 8 or PHP 8. The next version is planned to be compliant with both platform versions.

**Comment by jeffrey-simonds** [comment]
@geoffhumphrey I just posted this same issue. Is there a way for us to resolve it? Our competition is on Saturday 5/21 and we've been running fine until last night when someone tried to register and received this error. It's also preventing us from assigning judges to tables. Bit of a crunch to get this ironed out so any help would be much appreciated.

**Comment by earthlogic** [comment]
@geoffhumphrey In reference to jeffrey-simonds comment (I'm working with him on this)...

Nothing changed a.) on our server, b.) in our installation or c.) software settings over the last couple days and this error all of a sudden appeared after working perfectly for the last 45 days. I tested and see this error any time we try to register a new judge using quick or standard method.  

In case it helps, here is one article on this error.  https://sebhastian.com/mysql-truncated-incorrect-double-value/#:~:text=The%20MySQL%20error%20Truncated%20incorrect,mistake%20in%20UPDATE%20statements%20script.

**Comment by geoffhumphrey** [comment]
Hi @jeffrey-simonds and @earthlogic - I'm investigating. 

That said, however, since you are in a time crunch, you may want to see if the [latest master commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/tree/dbc6685d704b69a75e48881b743301336d2047f7) will alleviate your issue - there has been some significant rewriting/re-deployment of SQL-related programming to utilize prepared statements. I've successfully tested all affected functions in my test environment (running PHP 8.0.15 and MySQL 8). 

Of course, make sure to back up your current DB and deploy the commit as separate instance, just in case.

**Comment by earthlogic** [comment]
Thanks Geoff.  Assuming the latest commit is 2.4.0.3 released on Jan 24, 2022, we're already using it.  Let us know if you find anything.  Appreciate your time and assistance.

**Comment by geoffhumphrey** [comment]
Actually, what I'm referring to is an unreleased code build of what will be incorporated into the next release, 2.4.1. Here's a [direct link](https://github.com/geoffhumphrey/brewcompetitiononlineentry/archive/dbc6685d704b69a75e48881b743301336d2047f7.zip) to that build's archive.
