### ISSUE TITLE
Error Message When Trying to Manage Entries

### ISSUE THREAD

**Issue by cgeerdts** [geoffhumphrey/brewcompetitiononlineentry#1319]
Version:
Not sure

Installation URL:
https://bellinghamhomebrewersguild.org/bestofthebay/

Is your installation hosted on brewcompetition.com or brewcomp.com?
Not sure

Description of Issue:
When I try to click on "Manage Entries" I get the following error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE brewBrewerID='default' AND brewPaid='0' AND brewReceived='1'' at line 1". I am not sure why the error is occurring. Please let me know how I can get to the manage entries page to help with organizing for the competition. 

Thanks,

Cory

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @cgeerdts, apologies for my tardy reply. I've been on vacation since July 4 until yesterday. Are you still experiencing the error? If so, your web server is probably running PHP 8, which BCOE&M version 2.4.0 does not support (version 2.5.0 will). 

It appears you're using Bluehost as your hosting provider. You (or your web master) can choose the version of PHP that your domain and subdomains are running via Control Panel. [This help article](https://www.bluehost.com/help/article/php-version-selection) provides more information and directions.

**Comment by cgeerdts** [comment]
Thanks Geoff,
We were able to get this error resolved. We are still having issues with
logging back into the website after an account is created. The only way we
can log in is by creating a new password with the "Forgot Password" link.
Do you know what could be the cause of the issue?

Cory

**Comment by geoffhumphrey** [comment]
Hi Cory. I was able to create an account, log out, and log back in with the password I specified without a problem just now. I was able to log in with Chrome, Edge, Firefox (all Windows), and Brave (iOS) with success.

Which leads me to think it's a local browser issue. Clearing cache and cookies may do the trick. Or, try another browser.

If that doesn't work, we'll have to dig deeper.

**Comment by cgeerdts** [comment]
It works for me as well. Not sure what changed between the last time I
tried it and now. Anyways thanks for getting back to me! Much appreciated.

Cory
