### ISSUE TITLE
Drop-off Location is Required in Sign-up Even for Volunteers

### ISSUE THREAD

**Issue by ramseybrews** [geoffhumphrey/brewcompetitiononlineentry#1329]
Version: 2.4.0

Installation URL: https://usopen.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? brewcomp.com

Description of Issue:
When people are registering a drop-off location must be set even if they are just trying to sign up to judge/steward. I don't see a way to change what is required in the user registration area but it is causing issues for people trying to sign up.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @ramseybrews, apologies for the tardy reply here. Currently, there isn't a way in the UX/UI to "turn off" the requirement. 

For the Amateur Edition of BCOE&M, a drop-off option is required for all participants since judges, stewards, and staff can also be entrants (that's not the case with the Professional Edition). At present, there is a _Not Applicable / Shipping Entries_ option included for just this purpose. 

However, I can see your point about this being somewhat confusing. In the next version, the modifier will be changed to "Entry Delivery," the _Not Applicable_ choice will be separated from _Shipping Entries_ in the drop-down, and more robust explanations will be provided directing those who are creating accounts who do not plan on submitting entries to chose _Not Applicable_.

Hope that helps.
