### ISSUE TITLE
Version 2.4.0: Unable to add BOS entries and display on the results page

### ISSUE THREAD

**Issue by SWBSAV** [geoffhumphrey/brewcompetitiononlineentry#1336]
Version: 2.4.0

Installation URL:  https://savannahbrewers.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com?  brewcomp.com

Description of Issue:  I'm trying to display BOS winners.  When I try to select BOS entries, nothing shows.  I have a customer category and the styles are assigned to the category.  I have been searching through all the settings but I can't find why this will not let me add BOS entries and display the results.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @SWBSAV, thanks for reporting. I've tracked down the issue and have implemented a fix for you since you're a hosting subscriber. You will be able to go in and delineate your BOS entries now. Apologies for any confusion.

For non-hosted installations experiencing the same issue, the character limit for the scoreType row in the judging_scores DB table was set too low. Running the following command will change that character limit (if you're using a prefix, be sure to add it before ``judging_scores``:

```
ALTER TABLE `judging_scores` CHANGE `scoreType` `scoreType` CHAR(4);
```

If you have any scores of entries that have a custom style type, there are two ways to fix them in the DB:

1. Update the DB directly via phpMyAdmin with the correct scoreType (relational to the style_type table's id for the custom style) for each of the affected entries.
2. Go to Admin > Scoring > Manage Scores and delete any placing entries that have custom style types. Then, re-enter the scores and their associated places. 

Hope that helps.
