### ISSUE TITLE
Version 2.4.0: Unable to register new judges today 

### ISSUE THREAD

**Issue by konevik** [geoffhumphrey/brewcompetitiononlineentry#1340]
Version:2.4.0

Installation URL:https://doggdayzz.brewcomp.com/

Is your installation hosted on brewcompetition.com or brewcomp.com? Yes

Description of Issue: Previously no problems, but today a person signing up to judge at our competition reported that they were unable to create their account. I tried to create an account for them from the admin side, both via the "Register a Judge (standard)" and "register a judge (quick)" pages. I fill out all their information, hit the recaptcha and press the Register button. Screen goes black with spinning gear (working, please stand by) for ~30 seconds and then back to the register screen. All the fields are still filled in. The recaptcha has a checkmark next to it. I can hit register again and it repeats the above. After this the recaptcha says verification expired, check the box again. I do so and above repeats. 

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by konevik** [comment]
This seems to be isolated to one user, "Butler," other accounts are adding without difficulty. They are a husband and wife team, trying to register their beer entries under a "couples" account, and 2 separate judging accounts. 
I removed the BJCP id from the couples account, but still can't create an account (different email) for the wife. 
I think I'm just going to use the "couples" account for her judging sessions as it is letting me do that.

**Comment by geoffhumphrey** [comment]
This can be an issue if they're trying to use the same email address for two different accounts. The system will not allow that since email addresses serve as usernames within the system. But since you're using another email address and issue persists, it raises a concern.

Feel free to DM or email me the credentials you're attempting to use to register and I'll see if I can recreate the issue.

**Comment by kmeintsma** [comment]
We have the same issue, and it's not a case of same email address. Only one person has been affected.

I even tried the multiple methods for registering an account with full admin priveledges, and different browsers. 

No joy.

It's time to assign judges and volunteers so this is becoming a bit of an issue. We host our own server. We are running 2.4.0(e).

**Comment by kmeintsma** [comment]
GOT IT!

Just through random luck after multiple attempts today, I selected EVERY SINGLE JUDGING session, and it let me register the person. This is not desirable, but it is a workaround.

**Comment by geoffhumphrey** [comment]
@kmeintsma - Of course, that's not optimal, but at least it's a work-around. I'll look into why that's the case.

**Comment by kmeintsma** [comment]
I have a more detailed question and can't find anything in the software or
in the help system to answer it.

I have a large category (multiple actually) that I want to split into two
categories by sweetness for both judging and awards. How can I do this?

It's simple enough to create flights for a table that would be separated by
sweetness if I look at the entry information although it's extra work. But
awards are reported by table correct? I can't create extra tables as far as
I can tell and then assign flights to them based on the characteristics I'm
targeting.

I've added some additional judging sessions. When I try to assign judges to
a table by session, the software will NOT allow me to select the judges I
need. I presume it's because they didn't sign up for the session due to it
being created after signups were done. Is there a way around this?

**Comment by geoffhumphrey** [comment]
> I have a more detailed question and can't find anything in the software or in the help system to answer it.

Please see response in #1343.

**Comment by kmeintsma** [comment]
Now that I've identified the workaround, i think I can tell you what is
going on.

I think you've assumed that EVERY single choice must be made before
allowing the registrant to create the account. Because there is no error
reporting, the registrant has no clue that you are expecting them to select
something from each and every drop down box.

**Comment by geoffhumphrey** [comment]
This has been changed in the latest version (2.5.0 Beta and forward). Now, the default response for each judging session is "No" unless the participant changes it to "Yes." It is also more obvious that responses are required. See below...

![image](https://user-images.githubusercontent.com/5216502/195152484-34365511-750f-439e-8263-d2c48ca745ea.png)

Hope that'll make things more clear.
