### ISSUE TITLE
Allergens not showing on label generation?

### ISSUE THREAD

**Issue by woottonn** [geoffhumphrey/brewcompetitiononlineentry#1362]
Version: 2.4.0

Installation URL: https://hearthbc.co.uk/

Is your installation hosted on brewcompetition.com or brewcomp.com? No

Description of Issue: Am I right in assuming allergens should appear on the label generation so the judges are aware? Or does this information present itself to a judge elsewhere?

**Comment by geoffhumphrey** [comment]
Hi @woottonn - at present, allergens are not part of any label since there isn't a label option that encompasses all entries - and allergies could be present in any entry. The only option for judging labels as of now are those with required info (SHV, Fruit Beer, Experimental Mead, etc.).

However, allergens **are** listed on all pull sheets (for use by in-person judging sessions) and on all electronic judging scoresheets if you're using the Electronic Scoresheets option. 

Additionally, there is the Possible Allergens in Entries report available that contains a list of entries that have possible allergens - go to Admin > Reports > Allergens > Possible Allergens in Entries to get that report.

**Comment by geoffhumphrey** [comment]
> At present, allergens are not part of any label since there isn't a label option that encompasses all entries - and allergies could be present in any entry. The only option for judging labels as of now are those with required info (SHV, Fruit Beer, Experimental Mead, etc.).

I misspoke here (misremembered, maybe?). There is a label option that will print labels for **all** entries called _With Required Info - All Styles_. For the next version, allergen info will be added to both this label option and the _With Required Info - Only Styles Where Required_ option. 

The output will look similar to this:
![image](https://user-images.githubusercontent.com/5216502/196000443-7fcbbedb-c001-4842-9e58-b066dc96a7e9.png)
