### ISSUE TITLE
Enhancement: Remove Character Limit For Integrated/Online Scoresheets

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#1370]
[BCOE&M](http://www.brewcompetition.com/) 2.4.0 (e) Hosted Amateur Competition Edition 2009-2022

Judged at a comp last weekend that used the integrated online scoresheets, and on the vast majority of entries we ran into the character count limit (particularly for Flavor, and especially on mead scoresheets)

I would suggest no character limit at all (we need the freedom to write as much as required when judging -- in a handwritten comp I will often go to the back of the sheet, and my handwriting is kinda small!), but if there is a programatic or database reason it must be there, it needs to be significantly higher than what it currently is.

**Comment by BrewDrinkRepeat** [comment]
Hi Geoff, sorry for not seeing your question sooner.

We were using the Classic scoresheets, not the structured. I see you already updated them, thank you!

I like ercousin's suggestion as well, we've all gotten scoresheets (from judges who should know better!) that were appallingly short on detail. I once entered an American Brown, and a National judge wrote for aroma "caramel and malt". 

Three words, one of which doesn't count, and one of which is so general as to be meaningless. :(

**Comment by geoffhumphrey** [comment]
While I do agree that some judges are appallingly terse and pithy when they should be providing more feedback, I'm not sure that forcing a certain word or character count will really address the entire issue. It is certainly possible from an UI standpoint - and pretty easy to implement - but it may not be the panacea that you're looking for, despite the fact I do agree that three words from a National judge is pathetic.

It's for this reason that I've switched to the Structured Scoresheet for all comps I'm either the organizer or judge coordinator for. At least with that one, especially electronically, they HAVE to provide a "tick" for each data point, which does provide a modicum of feedback for entrants.

**Comment by geoffhumphrey** [comment]
> Hi Geoff,
> 
> As an aside, what do you think of configurable "Minimum" and "Recommended" word or character counts for these scoresheets?
> 
> I know I would love to be able to force judge to write more than 3 words with a 5-10 word minimum, while still telling them I expect 30 words.
> 
> Thoughts? If it's a decent idea, I can file a new Issue as Enhancement Request.

@ercousin and @BrewDrinkRepeat, I spent some time last night and added the ability for Admins to designate a minimum number of words judges must use when providing comments. If enabled, the minimum number will be enforced for all comment fields on the Classic Scoresheet and Checklist Scoresheet, as well as the Overall Impression comment/feedback field on all Structured Scoresheets. 

Minimum Word Count Not Reached
![image](https://user-images.githubusercontent.com/5216502/205388778-8f70a594-8265-4548-99d0-ae98a345d048.png)

Minimum Word Count Reached
![image](https://user-images.githubusercontent.com/5216502/205389517-4173ab9e-8f1a-42ef-acca-a48b9ce26b98.png)

**If a minimum word count is specified**, judges will not be able to submit a scoresheet if they do not provide the minimum number of "words" (note that "words" is in quotes since the scripting cannot decipher whether the input is actually a word in any language - in essence, judges could get around the minimum by simply typing random letters with spaces in between).

![image](https://user-images.githubusercontent.com/5216502/205389858-ba62c730-6d46-4d37-8118-0d1dc7382e73.png)

Code is included in the latest master commit and will be available when 2.5.0 releases this month. 

To enforce a minimum word count, Electronic Scoresheets must be enabled in Admin > Preferences > Website Preferences and a number must be designated in Admin > Preferences > Competition Organization Preferences.
