### ISSUE TITLE
Version 2.5.0 beta: Need at least 2 judging sessions for judges to set availability in account edit 

### ISSUE THREAD

**Issue by jimmyorkin** [geoffhumphrey/brewcompetitiononlineentry#1372]
**Verify the Following**
Reporting About the Latest Version? Yes, latest commit

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.5.0 beta
Installation URL: 
Hosted Installation? No

**Describe the Bug**
There must be at least two judging sessions to be able to select judging availability in judge account edit.

I had only one session and there was no selection in the judge edit account page for session availability. Added a second and the selections appeared.

**To Reproduce**
1. Create competition with 1 judging session
2. Go into edit account for a judge. There will be no sessions in the edit page to select.

**Expected Behavior**
Be able to select a judging session even if there is only one session.

**Screenshots**

Broken:
![image](https://user-images.githubusercontent.com/13592817/201499151-a29d631f-753c-4d5e-a05c-3903e7e71689.png)

Working:
![image](https://user-images.githubusercontent.com/13592817/201499099-f388fdb1-f1d2-4656-a64b-e2ae5507038b.png)

**Server Environment**
- PHP Version: 8.0
- MySQL Version: 
- Other Info: [if applicable. Apache, nginx, etc.] Apache in xampp

**Local Environment**
 - OS:
 - Browser: 
 - Browser Version:

**Additional Context**

**Comment by geoffhumphrey** [comment]
Hi Jimmy - this is by design, actually. If there is only one session, it stands to reason that if someone is signing up to serve as a judge (or steward), they are available for that single session being offered. There's scripting in place to mark any judge or steward as a "yes" for this single session upon registration.

If a comp has only one session, everyone is _available_ for that session. Now, whether admins assign those people to the judge or steward pools is up to their discretion.

**Comment by jimmyorkin** [comment]
Ah, that makes sense. It confused me while testing. Good to know it is designed for that.

Thanks.
