### ISSUE TITLE
Version 2.5.0 - Specialty Spice Beer - Unable to Add Score

### ISSUE THREAD

**Issue by SWBSAV** [geoffhumphrey/brewcompetitiononlineentry#1374]
Version:  hosted

Installation URL:  savannahbrewers.brewcomp.com

Is your installation hosted on brewcompetition.com or brewcomp.com?

Description of Issue:
I am unable to enter a score for one of the entries on a table.  When I do, I get a spinning gear icon and the score never saves.  I am able to enter scores for all other entries on the table and in the competition.  It's only the one entry that will not save.

For enhancements, please prepend "Enhancement - " to the title. For issues/bugs, please prepend the BCOE&M version number the title.

**Comment by geoffhumphrey** [comment]
Hi @SWBSAV - this has to do with that entry's particular style as entered by the participant (Specialty Spice Beer). The style type was missing blank in that style's database record. And due to that, the save function could not complete, producing the spinning gear. 

I've corrected the issue on your installation and you can now enter the appropriate score. 

If this is an issue for any non-hosted installations, changing the brewStyleType column value to 1 in the Specialty Spiced Beer DB record (via phpMyAdmin or shell access) will alleviate this issue.

**Comment by geoffhumphrey** [comment]
This fix was omitted for any installations that already had BJCP 2021 styles installed. Will be included in the 2.5.1 release. In the meantime, all hosted installations have been updated and those who are self-hosted and experiencing this issue, the fix described above will alleviate the issue.
