### ISSUE TITLE
Version 2.5.0 Judging Sessions not working correctly

### ISSUE THREAD

**Issue by AwMelch** [geoffhumphrey/brewcompetitiononlineentry#1385]
**Verify the Following**
Reporting About the Latest Version? not sure 

Searched Issue Reports for Bug? Yes 

Reviewed the Good To Know Issue Reports? Yes 

**BCOE&M Info**
Version: 2.5.0
Installation URL: https://bockfest.brewcomp.com/
Hosted Installation? Yes

**Describe the Bug**
Judging sessions don't show up on the hosted site, nor in the Judging Sessions page. However, when I view the "All cometition dates" there are now 8 judging sessions show (a few ppl tried look at the site to add a session and everyone added) but they continued to not show up in the dashboard or main hosted site. 

**Expected Behavior**
Judging sessions should be visible and/or able to be deleted

**Screenshots**
see attached

**Local Environment**
 - OS: Mac for me, Windows for another user
 - Browser: Chrome for me, not sure for other
 - Browser Version:
![unnamed](https://user-images.githubusercontent.com/120532446/207474936-ad50401c-c018-44ce-8786-4debb272209e.png)

**Additional Context**

<img width="996" alt="Screen Shot 2022-12-13 at 7 32 23 PM" src="https://user-images.githubusercontent.com/120532446/207475252-9a9e5513-0971-4e8e-b245-8889f10dda12.png">

**Comment by geoffhumphrey** [comment]
Hi @AwMelch, thanks for reporting. This issue was reported via Issue #1381 and was incorporated into the core 2.5.0 code earlier this week. If you are experiencing the same issue, make sure your 2.5.0 code is updated through [tag 2.5.0.2](https://github.com/geoffhumphrey/brewcompetitiononlineentry/tree/v2.5.0.2).

Unfortunately, as of this writing, I haven't updated hosted installations with the latest 2.5.0 code yet. 

I've fixed the issue on your installation by directly editing the database. If you would, please hold off adding or editing judging and non-judging sessions for the next couple of hours.

Fortunately, this issue is isolated to only hosted installations. I'll will update all hosted installations with the correct version code later tonight. My apologies for any inconvenience this causes.

**Comment by AwMelch** [comment]
Thank you sir! Sorry for the extra work on our part

**Comment by AwMelch** [comment]
and I do promise i tried looking before i submitted. I've never used
GitHub before tonight :)

**Comment by geoffhumphrey** [comment]
It's all good! That particular issue is closed, so it's not easily found on the issues list in its default state (only open issues). I've updated your installation and all other hosted installations. Should be good to go now. Best of luck with the comp!!

**Comment by AwMelch** [comment]
Hi Geoff, I replied to the prost@ email for a billing issue with our site,
but not sure if it reached you. You sent it to Rob Westendorf for our
Bockfest.Brewcomp site that needs renewal. How do I get this taken care of
for you/us?

thanks
Andrew

**Comment by geoffhumphrey** [comment]
Hey, Andrew. I did get it and replied with a renewal link to your Gmail address at ~11:50 AM yesterday (Mountain). Maybe it's in your spam folder? I'd rather not post that link here on a public forum. Let me know if you'd like me to send it again.
