### ISSUE TITLE
Version 2.6.0: "There are no available sub-styles." when trying to add a table

### ISSUE THREAD

**Issue by AdrienM76** [geoffhumphrey/brewcompetitiononlineentry#1434]
**Verify the Following**
Reporting About the Latest Version? Yes (but this existed in 2.4.0 as well)

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.0
Installation URL: https://bataille.deadyeast.org
Hosted Installation? No

**Describe the Bug**
I am in Tables Planning Mode and cannot add any tables. Under 'available styles' there is a message "There are no available sub-styles". The 'Add Table' button is disabled.

Note, I'm not sure why Step 1 of Tables Planning Mode is to assign judges to the pool. It isn't necessary to know who your judges are before deciding how to organize your award categories. (aka 'tables') We're months away from the competition and it isn't even open yet for entries. But I know the styles we're taking and I have an idea based on previous competitions what award categories we will likely use. We assign judges to tables they can judge, not the other way around, never have, and this wasn't a problem in the past.

I assigned a judge to the pool anyway. That didn't help.

Perhaps because we aren't taking entries yet, the Planning Mode won't let me create tables? (though I thought the requirement *not* to have entries yet was the whole point of this mode.)

And indeed, after moving my entry window up and adding an entry for myself, I can now add styles/sub-styles to tables, (and thus create a table) but *only* those styles/sub-styles that have entries.

Effectively, until the comp opens for entries, I can't plan my tables. And I can't add sub-styles to tables once it does open, until those sub-styles have entries. So I can't really 'plan'.

**To Reproduce**
1. Go to Admin Dashboard > Organizing > Tables > Add
2. See error

**Expected Behavior**
Tables can be added, assigning styles/sub-styles in Planning Mode without needing to have judges assigned to the pool, or entries in the system.

**Server Environment**
- PHP Version: 7.4.33
- MySQL Version: 5.7.39-42-log
- Other Info: Apache

**Local Environment**
 - OS: MacOS 12.6.7
 - Browser: Safari
 - Browser Version: 16.5.2

**Comment by geoffhumphrey** [comment]
You are correct. The concept of Tables Planning Mode is to set up tables AFTER entries have been added to the system, but BEFORE you've actually sorted and checked them in. 

The mode was envisioned to be used toward the end of the comp's entry window and/or right after it ends, allowing Admins to get a jump on creating tables and assigning judges in the hours and days before sorting is scheduled. This way, for example, you can assign tables/award categories ahead of time to distributed sessions and, in turn, assign judges to those tables, setting aside the associated entries during sorting instead of after the fact.

I certainly understand why you'd want to get a jump on organizing your competition tables/award categories, especially if you are confident in your knowledge of what those award categories will be. However, the planning mode was not conceived to be used until there were logged entries into the system.

**Comment by geoffhumphrey** [comment]
As an FYI, please see Issues #882, #1142, #1230, #1388, and #1418 for more information and insight into why Tables Planning Mode was implemented in this way.

**Comment by AdrienM76** [comment]
Good to know, thanks. Though I'd request removing this restriction as an enhancement if it isn't too much trouble. I see the immediate use cases in those Issues but I don't see a reason why it can't be used earlier in the process as part of setting up a competition as that doesn't seem to be mutually exclusive. (other than, 'there is too much code to change' which is fine)
