### ISSUE TITLE
Version 2.6: Entries with Possible Allergens display as Unconfirmed Entries

### ISSUE THREAD

**Issue by diatonic** [geoffhumphrey/brewcompetitiononlineentry#1442]
Reporting About the Latest Version? Yes 

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6
Installation URL: (non-public upgrade test)
Hosted Installation? No

**Describe the Bug**
Upgraded our 2.5.0.2 installation to 2.6. Entries that previously displayed "possible allergens" now also showed "Unconfirmed Entry. Edit or contact the participant to confirm."

**Screenshots**
Entries on version 2.5.0.2:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1490527/6e0a2c57-cc4f-48d0-af8d-4640b3a14be4)

Entries after upgrading to 2.6:
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/1490527/cdc23f13-323a-4450-921b-20c10f0ceacf)

**Server Environment**
- PHP Version: 7.3.33
- MySQL Version: 5.5.5-10.3.35-MariaDB
- Other Info: Apache/2.4.37 (AlmaLinux)

**Local Environment**
 - OS: Windows 11
 - Browser: Firefox & Edge
 - Browser Version: Latest

**Comment by geoffhumphrey** [comment]
Hi @diatonic - thanks for reporting. Confirmed. There was some logic issues that I've since fixed. If you replace the /admin/entries.admin.php file with [the one in the last master commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/master/admin/entries.admin.php), it will resolve the issue.
