### ISSUE TITLE
MariaDB and JSON datatype not working well

### ISSUE THREAD

**Issue by donutbrew** [geoffhumphrey/brewcompetitiononlineentry#1454]
**Verify the Following**
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes
Originally was related to #1431 but this may be a distinct issue

Reviewed the Good To Know Issue Reports? Yes

**BCOE&M Info**
Version: 2.6.0.1
Hosted Installation? No

**Describe the Bug**
JSON content does not get parsed for display.

**To Reproduce**
1. Install fresh BCOEM 2.6.0.1, and run through set up on fresh database
2. Go to 'index.php'
3. Scroll down to 'Rules'
4. See a bunch of un-parsed JSON

**Expected Behavior**
Text should be parsed from the JSON format and displayed in a readable format, however, all of the JSON syntax and escape chars render as is on the homepage.

**Screenshots**
<img width="897" alt="image" src="https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/6391757/643435c2-1972-476f-8e0b-7768122f74ab">

**Server Environment**
- PHP Version: 7.3.33
- MySQL Version: 11.0.3-MariaDB
- Other Info: [if applicable. Apache, nginx, etc.]

**Local Environment**
 - OS: 11.0.3-MariaDB
 - Browser: Safari
 - Browser Version: 16.5

**Additional Context**

I updated to MariaDB 11 to avoid setup failures described in #1431. That does allow setup to make it through without error. However, places where BCOEM is pulling JSON data, it seems that at least in the Rules section, it is not getting parsed. I haven't combed through the PHP, so it's possible the issue is there, but my first thought was in differences in how MySQL and MariaDB may be handling JSON datatypes.

Checking https://mariadb.com/kb/en/json-data-type/ :

> In MySQL, JSON is an object and is [compared according to json values](https://dev.mysql.com/doc/refman/8.0/en/json.html#json-comparison). In MariaDB JSON strings are normal strings and compared as strings. One exception is when using [JSON_EXTRACT()](https://mariadb.com/kb/en/json_extract/) in which case strings are unescaped before comparison.

Checking the JSON fields using `show create table test01_contest_info` the are created like this in MariaDB:

`` `contestRules` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`contestRules`)), ``

**Comment by geoffhumphrey** [comment]
I believe I've got a solution to the problem in the latest master commit. 

This appears to be only an issue for new installations during setup. Upgrading from an earlier version does not appear to affect it, even using MariaDB (which automatically changes the unsupported JSON type to LONGTEXT). So, it turned out that it didn't have to do with MariaDB vs other DB server types. The problem had to do with the update script being run a second time, which was altering the rules text by adding a bunch of slashes upon firing the json_encode command, thus messing with parsing.

Essentially, to fix this for use upon setup is to change [line 132 in /sites/bootstrap.php](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blob/0ff8741d3418ab1158637a8e30bc8d3e4e1e6975/site/bootstrap.php#L132) to:

``if ($force_update) include (UPDATE.'off_schedule_update.php');``

This will prevent the update script from firing again and the Rules should render correctly. 

If you're experiencing this after initial setup, you can simply go to Admin > Preparing > Competition Info and remove the extra slashes, etc. from the text.

**Comment by donutbrew** [comment]
Ahhhh--that makes sense, but it wasn't obvious to me at the time.

To confirm, I did pull master and install fresh--all looks good in a fresh installation. 
The only thing is I had to upgrade to PHP 8 in order to use the `str_contains()` function. That change may already be in your roadmap, but noting it here for folks coming by. 

I appreciate all you do!

**Comment by geoffhumphrey** [comment]
Ah, yes - good call. You are correct. The str_contains function is only in PHP 8. In the next commit, to make it PHP 7 friendly and to save confusion, I'll replace that function in both the /includes/constants.inc.php and the /update/off_schedule_update.php files with the good 'ol strpos function:

``if (strpos(strtolower($db_version), "mariadb") !== false) $db_maria = TRUE;``
