### ISSUE TITLE
Version 2.6.0: Random Entries Created Possible Bot Attack

### ISSUE THREAD

**Issue by Fencer04** [geoffhumphrey/brewcompetitiononlineentry#1461]
**Verify the Following**
Reporting About the Latest Version? Yes

**BCOE&M Info**
Version: 2.6.0
Installation URL: https://libme.brewcomp.com/
Hosted Installation? Yes

**Describe the Bug**
We are showing hundreds of beers over the entry limit, and a lot of entries have random characters as their information. It looks like a bot attack.

**To Reproduce**
1. Review the entries in our system.

**Comment by geoffhumphrey** [comment]
Hi @Fencer04. I'll be looking into this with a deep dive to root out the problem and where the vulnerability is. Fortunately, this actor only made themselves a nuisance and did not do anything than add 300+ entries into the system. I've removed the offending records and have also removed the two accounts that were used to post the entries.

Apologies for the issues. I'll keep an eye on your installation to make sure things don't repeat themselves.

**Comment by graemecoates** [comment]
There are a variety of issues here that I have found (testing against a test instance of 2.5.0). 

1. The form has nothing to prevent resubmission (eg using CSRF tokens or something similar). 
2. There is no server side check to ensure the submitted entries exceeds the number of allowed entries (but it does appear to check against number allowed per brewer from testing) - if a malicious user knows the form submission structure, they can bypass this check.
3. There is nothing to prevent the malicious user setting the "Paid" flag during the form submit, without ever having gone through a payment process (in the form, this is 0 for competitions that require payment, and 1 for those that do not).
4. There is no server side validation to prevent a user entering a beer as another user by changing both values of BeerBrewerID in the POST data. I have been able to submit an entry on behalf of an admin user as an ordinary registered user. 

Bulk input of data in the above ways is trivial using a tool like Jmeter - an attacker could quickly make a competition impossible to administer if the attacked added thousands and thousands of plausible paid entries. I'm not sure what other server side checks should be in place for this form (but otherwise aren't). I can supply a sample Jmeter script to demonstrate the above issues.

**Comment by geoffhumphrey** [comment]
Thanks @graemecoates for testing the 2.5.0 code! The [latest master commit](https://github.com/geoffhumphrey/brewcompetitiononlineentry/commit/5c69abbd265784d2111ea466abe53424e8e1b805) implements CSRF tokens and other code that I believe addresses the issues you raised. I spent the day testing, but cannot do any further for a few days. If you have an opportunity soon to test it out I would be grateful as I won't have the opportunity.

**Comment by graemecoates** [comment]
I'll try and check this out today.

**Comment by graemecoates** [comment]
Tested against 2.6.1e (cloned on 18th Sept 2023). 

* CSRF token (hidden field "token") is now working on this form - submissions with an incorrect/missing token return a 403. 
* User is unable to submit an entry when the limit is reached (the add entry page won't load; token missing - direct submit results in 403 as above). 
* Paid flags are ignored during entry submission (when fees apply) so user can't circumvent payment in this fashion.
* Altering BrewerID doesn't allow entry as another user.

This appears to resolve the issues listed above.
