### ISSUE TITLE
BCOE&M 2.5.0 - QR Broken Image 

### ISSUE THREAD

**Issue by NCBeerGuys** [geoffhumphrey/brewcompetitiononlineentry#1546]
**Verify the Following**
Reporting About the Latest Version? **Yes**

Searched Issue Reports for Bug? Yes
Searched QR and only three issues showed up - none related to a broken image QR code

Reviewed the Good To Know Issue Reports? Yes or No
*Please review the Issue reports that are labeled Good to Know. Find one and click on the label to view them all.*

**BCOE&M Info**
Version: 2.5
Installation URL: https://www.blueridgebrewoff.com/index.php?section=admin
Hosted Installation? Yes

**Describe the Bug**
The QR symbol for entrants to print out is a broken image. 

**To Reproduce**
1. Go to ['...'](https://www.blueridgebrewoff.com/index.php?section=admin#) 
2. Click on ADMIN > Preferences > Website
3. Scroll down to Entries > Styleset and Printed Entry Bottle Labels. We Selected BCOE&M with Barcode/QR Code 

**Expected Behavior**
When a user prints their entry label, the barcode should show up on the entry print out. It is now a broken image. 

**Screenshots**
![image](https://github.com/geoffhumphrey/brewcompetitiononlineentry/assets/174208002/15e15fd1-7398-4be4-9db5-de962e50829c)

**Server Environment**
PHP Version – 7.4.33;
MySQL Version – 10.5.22-MariaDB-cll-lve

**Local Environment**
 - OS: macOS 12.7.5
 - Browser: Chrome
 - Browser Version: Version 125.0.6422.142 (Official Build) (x86_64)

**Additional Context**
This is an urgent issue for the competition

**Comment by geoffhumphrey** [comment]
Hello @NCBeerGuys - Thanks for reporting. This issue has been addressed in the latest version, 2.7.0. Please see https://github.com/geoffhumphrey/brewcompetitiononlineentry/issues/1493 for fix details.

**Comment by geoffhumphrey** [comment]
Your installation appears to be back up and running 2.7.0. Please advise if the update has addressed your issue. Thanks!

**Comment by NCBeerGuys** [comment]
No, it has not. One of the developers offered the same solution but the
issue was discovered before the update to 2.7.0 - even as an admin, nothing
can be edited. It either goes to a 404 or doesn’t update but goes through
the process as if it did.

“Drink Local and Keep Your Beer Dollars in North Carolina!”

**Comment by geoffhumphrey** [comment]
OK. So, I'm crystal clear on things. Even though you've upgraded to 2.7.0 and all code in that package has been updated on your server, the barcode and QR codes are not populating on your chosen bottle label (I'm not able to verify since your entry window is closed). 

A few things. 
1. Please make sure that you've got all updated code in place on your for the QR code generation. That class is housed in the /classes/qr_code directory.
2. Verify that [this link](https://admin.brewingcompetitions.com/includes/barcode/html/image.php?filetype=PNG&dpi=300&scale=1&rotation=0&font_family=Arial.ttf&font_size=8&text=000001&thickness=20&code=BCGcode39) produces a barcode image for entry number 000001. This is address that v2.7.0 accesses.
3. Verify that [this link](https://brewcompetition.com/includes/barcode/html/image.php?filetype=PNG&dpi=300&scale=1&rotation=0&font_family=Arial.ttf&font_size=8&text=123456&thickness=20&code=BCGcode39) produces a barcode for entry number 123456. This address is used by versions prior to 2.7.0.

If all of those are in place and/or you're able to see the generated barcode labels, your server (or browser) may be blocking access to external scripts via http. Hosting companies vary in their PHP settings, so you'll need to consult their help files.

**Comment by NCBeerGuys** [comment]
My apologies for the misunderstanding - I saw the 2.7.0 in the subject and
my mind went to the current problem where we cannot update user info -
either by the user or admin. Our developer thought the update from 2.5
would have solved the problem and it didn’t.

The QR issue has been resolved and that ticket can be closed.



“Drink Local and Keep Your Beer Dollars in North Carolina!”
