### ISSUE TITLE
Version 2.7.1.1: Users unable to upload user_images (sponsors) or docs - undefined "FILTER" constants in handle.php (line 73)

### ISSUE THREAD

**Issue by graemecoates** [geoffhumphrey/brewcompetitiononlineentry#1574]
Reporting About the Latest Version? Yes

Searched Issue Reports for Bug? Yes

Reviewed the Good To Know Issue Reports? Yes

**Your Intallation's BCOE&M Info**
- Version: 2.7.1.1
- Installation URL: https://nationalhomebrewcompetition.org.uk/ 
- Hosted Installation? No

On attempting to upload images or docs (Sponsors, Scoresheets), a 500 error is thrown. Error in logs is:

[24-Sep-2024 06:20:12 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "FILTER_ENCODE_LOW" in /path/to/handle.php:73
Stack trace:
#0 {main}
  thrown in /path/to/handle.php on line 73

In line 73, you have:

$renamed_file = filter_var($renamed_file, FILTER_UNSAFE_RAW, FILTER_ENCODE_LOW | FILTER_ENCODE_HIGH);

None of the "FILTER" constants are to be found anywhere else in the codebase - `grep -R "FILTER_UNSAFE"` and `grep -R "FILTER_ENCODE"` only return handle.php on line 73. 

**To Reproduce**
1. Fresh 2.7.1.1 install.
2. Go to manage sponsors as admin
3. Try and upload an image
4. See 500 error happen

**Expected Behavior**

Images/Docs upload successfully 

**Server Environment**
- PHP Version: 8.2.20-1~deb12u1
- MySQL Version: MariaDB 10.11.6-0+deb12u1
- Other Info: Apache 2.4 + PHP-FPM

**Comment by graemecoates** [comment]
@geoffhumphrey Is this issue #1556 ? It looks similar in symptoms....

**Comment by geoffhumphrey** [comment]
This filter is expressly used to encode any potentially "unsafe" characters to the application that may be a part of the user-defined name of the file that will be uploaded. 

You are right that this probably be the line that is causing this issue and the one described in issue #1556. Changing it to the following will fire the filter with the correctly-named flags in place:

``$renamed_file = filter_var($renamed_file, FILTER_UNSAFE_RAW, FILTER_FLAG_ENCODE_LOW | FILTER_FLAG_ENCODE_HIGH);``

(Note that the flags should have been named ``FILTER_FLAG_ENCODE_LOW | FILTER_FLAG_ENCODE_HIGH`` - I don't know when, or if, those flags changed names recently. It may have been an oversight from the start.)

However, this may produce some results that are sub-optimal since this flag, now that it's implemented correctly, will encode characters in filenames with their corresponding ASCII entity numbers (e.g., [the character ø](https://www.ascii-code.com/CP1252/248) will be replaced with 248). 

With that in mind, this code does a good job of sanitizing the filename while avoiding turning most ASCII characters into their corresponding numbers. Replace the current handle.php lines 70-78 with this block:

```
// Get the file extension
$file_extension = pathinfo($filename, PATHINFO_EXTENSION);

// Get the file name without the extension 
$file_name = pathinfo($filename, PATHINFO_FILENAME); 

// Call function in common.lib.php to convert accented characters to ASCII
$file_name = remove_accents($file_name);

// Call function in common.lib.php to remove characters like &, $, etc.
$file_name = scrub_filename($file_name);

// Replace spaces with dashes
$file_name = str_replace(' ', '-', $file_name);

// Replace underscores with dashes
$file_name = str_replace('_', '-', $file_name);

// Remove any remaining special characters
$file_name = preg_replace('/[^A-Za-z0-9\-\_]/', '', $file_name); 

// Strip any html or php tags
$file_name = strip_tags($file_name);

// Strip any slashes
$file_name = stripcslashes($file_name);
$file_name = stripslashes($file_name);

// Failsafe in case the remove_accents function missed something
$file_name = filter_var($file_name, FILTER_UNSAFE_RAW, FILTER_FLAG_ENCODE_LOW | FILTER_FLAG_ENCODE_HIGH);

// Replace two or more dashes together with a single dash
$file_name = preg_replace('/-+/', '-', $file_name); 

// Add extension back
$renamed_file = $file_name.".".$file_extension;

// Make the filename all lowercase
$renamed_file = strtolower($renamed_file);
```

**Comment by graemecoates** [comment]
I have inserted the code given above for handle.php into a 2.7.1.1 instance, and it doesn't seem to fully resolve the issue. The upload page reports "The file has been uploaded successfully. Check the list to verify.", yet the file doesn't appear in the list of uploaded sponsor images. (Believe it's the same for the user_docs upload). It looks like there is an issue with a) undefined $filename variable, and b) (possible related) the movement of the temp file into the corresponding directory. 



[04-Oct-2024 09:40:42 UTC] PHP Warning:  Undefined variable $filename in /path/to/site/handle.php on line 71
[04-Oct-2024 09:40:42 UTC] PHP Warning:  Undefined variable $filename in /path/to/site/handle.php on line 74
[04-Oct-2024 09:40:42 UTC] PHP Warning:  unlink(/path/to/site/user_images/.): Is a directory in /path/to/site/handle.php on line 120
[04-Oct-2024 09:40:42 UTC] PHP Warning:  move_uploaded_file(): The second argument to copy() function cannot be a directory in /path/to/site/handle.php on line 123
[04-Oct-2024 09:40:42 UTC] PHP Warning:  move_uploaded_file(): Unable to move &quot;/tmp/php3kh08x&quot; to &quot;/path/to/site/user_images/.&quot; in /path/to/site/handle.php on line 123

**Comment by geoffhumphrey** [comment]
My apologies. Replace the first two lines in the block provided previously. 

```
// Get the file extension
$file_extension = pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);

// Get the file name without the extension 
$file_name = pathinfo($_FILES['file']['name'], PATHINFO_FILENAME);
 ```

For the version that is in the latest commit, I had converted the block to a function and neglected to change those two lines when copying from the function. Should work now!
