### ISSUE TITLE
Accented characters being scrubbed into DB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [geoffhumphrey/brewcompetitiononlineentry#270]
```
What steps will reproduce the problem?
1. Add / edit any DB field that goes through GetSQLValueString() with $theType 
== "scrubbed"

What is the expected output? What do you see instead?

utf-8 chars

What version of the product are you using? On what operating system?

trunk (r224)

Please provide any additional information below.

If $theType == "text" it works. Maybe it's just a matter of adjusting the 
$html_string array.
```

Original issue reported on code.google.com by `hades.hi...@gmail.com` on 1 Aug 2013 at 4:33

**Comment by rmsrosa** [comment]
I know this is closed and I hope I am not doing anything terribly wrong by commenting it here (I am new to this github stuff and I am not actually a software developer, so excuse me for this and let me know if this is not a proper way), but apparently this issue with the encoding has not been solved yet. 

Although the database is set to utf-8 and the html pages created by php are set to utf-8, the text is not being sent to the database in utf-8. I was having a big headache about this since I am translating the code to use it here in Brazil, in Portuguese. I finally found the solution. Just add the line

         mysql_query("SET NAMES 'utf8'");

in any file that queries the database for tables with text values. Place them somewhere before the queries. It is all fine, now.

Apparently someone with the proper access might be able to configure this directly in the php.ini file for the MySQL, but this might not be a solution for everyone. The solution above is probably more feasible and user-friendly.

If I have the time, I will fork and submit a pull-request with this, but since I am not familiar with this stuff, I thought it would be better to just write here the solution, in case someone else needs it.

Cheers!
