### ISSUE TITLE
BOS troubles

### ISSUE THREAD

**Issue by GraintoGlass** [geoffhumphrey/brewcompetitiononlineentry#483]
In trying to enter BOS results, for five categories--the fifth category (#28) does not appear, although selected as an accepted category. And, not able to post BOS winners--although #1 in the other four categories appears.

**Comment by graemecoates** [comment]
We saw a similar issue in the UK National competition (using the Beta) - I think the issue is the entries in judging_scores. We are missing 4 cats (1 where the BoS winner was!) - the corresponding row in judging_scores for each of the 4 missing cas has scoreType set to NULL, whereas the others are "1". See:

mysql> select * from judging_scores where scorePlace=1;
+-----+------+------+------------+------------+------------+-----------+--------------+
| id  | eid  | bid  | scoreTable | scoreEntry | scorePlace | scoreType | scoreMiniBOS |
+-----+------+------+------------+------------+------------+-----------+--------------+
|   1 |   95 |   32 |          7 |         40 |          1 | 1         |         NULL |
|   2 |  383 |   59 |         17 |         40 |          1 | 1         |         NULL |
|  11 |  268 |   52 |          6 |         42 |          1 | 1         |         NULL |
|  28 |  110 |   60 |         24 |         37 |          1 | 1         |         NULL |
|  57 |  427 |  144 |          8 |         40 |          1 | 1         |         NULL |
|  63 |  486 |  158 |         20 |         41 |          1 | 1         |         NULL |
|  76 |  479 |   13 |         18 |         40 |          1 | 1         |         NULL |
|  89 |  139 |    7 |         25 |         42 |          1 | 1         |         NULL |
| 108 |  473 |   73 |         15 |         45 |          1 | 1         |         NULL |
| 111 |  129 |   63 |         22 |         43 |          1 | 1         |         NULL |
| 134 |  422 |  142 |          1 |         33 |          1 | 1         |         NULL |
| 146 |  506 |  166 |         26 |         43 |          1 | 1         |         NULL |
| 183 |  541 |   91 |          5 |         34 |          1 | 1         |         NULL |
| 211 |  270 |   37 |         23 |         44 |          1 | 1         |         NULL |
| 227 |  207 |   67 |         28 |         43 |          1 | NULL      |         NULL |
| 233 |   67 |   49 |          2 |         43 |          1 | 1         |         NULL |
| 270 |  495 |   13 |         21 |         40 |          1 | 1         |         NULL |
| 279 |  191 |   77 |          3 |         47 |          1 | NULL      |         NULL |
| 315 |  312 |   31 |          9 |         45 |          1 | 1         |         NULL |
| 341 |  204 |   67 |         16 |         41 |          1 | 1         |         NULL |
| 355 |   38 |    9 |         19 |         40 |          1 | NULL      |         NULL |
| 373 |   57 |   16 |          4 |         40 |          1 | NULL      |         NULL |
+-----+------+------+------------+------------+------------+-----------+--------------+
22 rows in set (0.01 sec)

**Comment by graemecoates** [comment]
(The workround to at least display the scores is probably to update the rows in judging_scores, or to manually insert the row into judging_scores_bos). 

Haven't had time to hunt for the proper fix yet - assuming it's in the score entry routines.

**Comment by graemecoates** [comment]
I think this because brewStyleType for some styles is NULL from the beta release (for new 2015 styles)? These look populated in a full 1.3.1.0 release.  It looks like this carries over into:

<input type="hidden" name="scoreType<?php echo $score_id; ?>" value="<?php echo style_type($score_style_data[3],"1","bcoe"); ?>" />

within ./admin/judging_scores.admin.php.

eg

mysql> select brewStyleType from styles where brewStyleGroup=28 and brewStyleVersion='BJCP2015';
+---------------+
| brewStyleType |
+---------------+
|               |
|               |
|               |
+---------------+
3 rows in set (0.00 sec)


If I set these to "Ale" then everything works fine. A check for items like this would be useful - it's not obvious through the admin interface.
