### ISSUE TITLE
Add judge / steward

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#511]
I'd like to be able to add a judge / steward just by name, without the email, address, etc.

**Comment by geoffhumphrey** [comment]
The next version will have a "Quick Register" feature for admins to add judges or stewards, well, quickly. However, since the system relies on unique email addresses for usernames, an email address will be required. It also would be best practice to provide an true email for judges, especially if using the system to print scoresheet labels.

Link from the Admin Dashboard:
![V2 Entries and Participants Admin Dashboard](https://cloud.githubusercontent.com/assets/5216502/12183671/8ef98472-b54d-11e5-9ca5-f549d24e4773.png)

Quick Register Screen
![Quick Register a Judge or Steward](https://cloud.githubusercontent.com/assets/5216502/12183748/fb77bd94-b54d-11e5-89ef-ae521119230d.png)

**Comment by PeterSteinberg** [comment]
Thanks.

I can live with having to enter an email address.  I get people emailing to volunteer at the last minute so I have their name and email address, just not the rest of the data when I need to get everything set up.
