### ISSUE TITLE
Specifying brew strength on 21B styles for 2015

### ISSUE THREAD

**Issue by jimpdx** [geoffhumphrey/brewcompetitiononlineentry#512]
Hello Geoff. We are setting up a competition for next May which will only feature IPA (21A, 21B and 22A). As such I am duplicating the style rows for 21B so the user can select Red, White, Brown, Black IPAs, etc. However after examining the tables extensively I do not see how to setup a selector for "Strength" like you would for Meads? Per the specification:

> Entry Instructions: Entrant must specify a strength
> (session, standard, double); if no strength is specified, standard
> will be assumed. Entrant must specify specific type of
> Specialty IPA from the library of known types listed in the Style
> Guidelines, or as amended by the BJCP web site; or the entrant
> must describe the type of Specialty IPA and its key
> characteristics in comment form so judges will know what to
> expect. 
> Strength classifications:
> Session – ABV: 3.0 – 5.0%
> Standard – ABV: 5.0 – 7.5%
Double – ABV: 7.5 – 10.0%

**Comment by jimpdx** [comment]
I found these values under Mead specific fields. Is there a plan to generalize this design to support style-specific indicators?

**Comment by geoffhumphrey** [comment]
It shouldn't be too difficult. However, for now, make sure that users enter the strength as part of the "special ingredients" field that they are supposed to fill in.

**Comment by jimpdx** [comment]
@geoffhumphrey will "strength" and other classification fields be in a generic architecture going forward  (v2+) so that you can configure them to be displayed for ALL styles?

**Comment by geoffhumphrey** [comment]
For v2.0.0, since this only affects a few styles, the requirements for beer color and/or strength will be entered by participants using what was once called the "special ingredients/classic style" field. For 2.0.0, it will be labeled "Specific Type, Special Ingredients, Classic Style, Strength, and/or Color" and the help text will read "This sub-category requires that you specify a specific type, any special ingredients, a classic style, strength (for beer entries), or color." Similar to issue #522.
