### ISSUE TITLE
Conflicts Between Multiple Installs

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#528]
I have two installs of BCOE&M on my club site and recently they started to conflict somehow.

Randomly one will display the name of the other. Today all the Site Preferences (including paypal info) appeared to have copied itself from one install onto the other.

One install is 1.3.0.4, the other is 1.3.2.0.

We think something might be wrong with the browser caching where it is holding onto the site info of the first site opened, when opening two.

Both sites have different SQL databases and different SQL passwords.

Here are a few screenshots...

![image](https://cloud.githubusercontent.com/assets/1551339/12765179/5c6a790c-c9cb-11e5-8173-4a5cf8dd3c31.png)

![image](https://cloud.githubusercontent.com/assets/1551339/12765283/f999ae8c-c9cb-11e5-86a1-0227bfcb4134.png)

**Comment by geoffhumphrey** [comment]
Yes, this is a known issue with multiple installs. It does have to do with browser caching of session cookies. On the list for resolution - still researching...

**Comment by geoffhumphrey** [comment]
Until implementation of unique session names for sub-folder installations is complete, serving each installation from a sub-domain instead of a sub-folder will eliminate this issue (if that's possible for your environment). 

For example, in your case Eric, you could set up http://brewslam.gtabrews.ca and http://seasonal.gtabrews.ca for each of your instances. Again, if that's possible for your web hosting account.
