### ISSUE TITLE
Registration did not open

### ISSUE THREAD

**Issue by leswright** [geoffhumphrey/brewcompetitiononlineentry#536]
Our competition registration date started this morning but there is still no link for registering on any of the pages.  Config.php $setup_free_access is set to FALSE.  I verified the dates and times and even changed them to a week earlier but no luck.  Is there anything else I need to change or verify to open registration?  Version is 1.3.2.0.  The URL is http://www.brewmastersopen.com if needed.  This is my 3rd year using the software so hopefully I haven't made a rookie mistake. Thanks!

**Comment by wireden** [comment]
I recommend checking your site folder in the config file.

The url http://www.brewmastersopen.com/bcoem/index.php?section=register. Will allow you to register.

`Set the base URL of your installation. In most cases the default will be OK. 

IF YOU ARE RUNNING YOUR INSTANCE OF BCOE&M IN A SUBFOLDER...
Add the name of the subdirectory between the quotes of the $sub_directory 
variable.
* Be sure to INCLUDE a leading slash [/] and NO trailing slash [/]!

Example:
$sub_directory = "/bcoem"; 

WARNING!!!
IF you do enable the subdirectory variable, YOU MUST alter your .htaccess file
Otherwise, the URLs will not be generated correctly.

Directions are in the .htaccess file.

*/

$sub_directory = "/bcoem";

/*
`

**Comment by leswright** [comment]
Thank you for the quick reply.  I was just reading an earlier problem report and one of the recommendations was to change the file permissions to 766 or 777.  When I checked my server files almost all were 755, changing them to 777 enabled registration and all the pages.
Thanks again!

**Comment by wireden** [comment]
Also check.

If you are a top-level admin and are seeing this error page when accessing the a public page such as the "Rules" page, your server may not be able to accommodate search engine safe (SEF) URLs. If you are a top-level administrator of the site, log in now and adjust your site preferences.

I had to change that setting to get my links to work.

**Comment by geoffhumphrey** [comment]
I just checked your site; looks like registration has opened. Thanks to @wireden for helping out here!
