### ISSUE TITLE
"added" style not selectable in pulldown menu

### ISSUE THREAD

**Issue by HillbillySasquatch** [geoffhumphrey/brewcompetitiononlineentry#545]
I have created a special style (Category 36A in my case) but it doesn't show up as a selection in the pull down menu for available styles when making entries.

http://thirstyorangebrewoff.brewcomp.com/

**Comment by geoffhumphrey** [comment]
@HillbillySasquatch (love the name), after looking into the issue, the custom style you have defined is active and on the drop-down list. It's the absolute last item on the list and was being "covered" by the footer.

Since your site is hosted, I disabled the custom styling for the drop-down menu, leaving the browser default. The style is there at the end of the list for entrants to choose.

For others having this problem, change this line in the /sections/brew.sec.php file, on or near line 235:
`<select class="selectpicker" name="brewStyle" id="type">`
To:
`<select name="brewStyle" id="type">`

That will take care of the problem.
