### ISSUE TITLE
Judge ranks appearing as "Array" in NHC database (Seattle)

### ISSUE THREAD

**Issue by jimpdx** [geoffhumphrey/brewcompetitiononlineentry#554]
Not sure if this is a systemwide bug or just reported by the Seattle Judge coordinator but he is unable to see judge ranks when viewing the available judge report?

**Comment by geoffhumphrey** [comment]
Hello @jimpdx - the version of BCOE&M used for the NHC is heavily augmented for their purposes. I made some big changes to the base code back in 2013 to accommodate the AHA's needs, but since then it's been customized even further. I would send an email to  info@brewersassociation.org to let them know about this issue - attention: Shane Wood, IT Director.
