### ISSUE TITLE
Missing drop locations

### ISSUE THREAD

**Issue by dducrest** [geoffhumphrey/brewcompetitiononlineentry#555]
The link to the drop location does not have any drop locations on the page. 3 locations are defined and the list can be viewed from the Admin panel

http://homebrewclassic.brewcompetition.com/entry#drop

**Comment by geoffhumphrey** [comment]
Confirmed. The info that is not displaying formerly was dependent upon the entry window close date. Now that shipping and drop-off close dates are delineated expressly by admins, the information should appear on the entry info public page. 

@dducrest, since your sites are hosted, I've updated the code on both to display drop-off and shipping information there since those two close dates have not passed as of yet...
