### ISSUE TITLE
0.75" round label error:  FPDF error: Unknown label format: OL5275W

### ISSUE THREAD

**Issue by ryanroat** [geoffhumphrey/brewcompetitiononlineentry#588]
When I try to create 0.75" round labels for the full set of entry or judging numbers, it fails with FPDF error: Unknown label format: OL5275W.

Style/Sub-Style only works as expected as does Entries Added By Admins.  0.5" round labels work as expected as well.

**Comment by geoffhumphrey** [comment]
Hi Ryan, thanks for reporting. This is a known issue that has been fixed in the latest 2.0.1 commit. Specifically, the fix applies to the /admin/default.admin.php file on lines 393, 400, and 404 (the "R" was left off of the label format URL parameter on those links). 

Thanks for your report. A fix for this issue will be in the next release.

**Comment by ryanroat** [comment]
Hi, thanks for the quick response. We need to print in the next couple days.  You pointed out specific lines, 393 and 404, which were already correct in our installation, but since you explained what to look for and approximately where, I was able to update lines 371 and 382 myself which were not correct.  .  It's working now.  Cheers!

**Comment by geoffhumphrey** [comment]
Good catch. Glad it's working for you now!
