### ISSUE TITLE
Editing BrewStyleCategory in db

### ISSUE THREAD

**Issue by jlawless1** [geoffhumphrey/brewcompetitiononlineentry#598]
I am running BCOE&M 2.0.1 at http://www.clarksvillecarboys.com/NSBO/2016/. Our competition is running a modified version of the 2015 BJCP guidelines similar to what the NHC has in 2016 but not as comprehensive. I wanted to use the software to run the competition as if the styles were native to the software. To do this I have edited the elements of the database to reflect this, http://www.clarksvillecarboys.com/NSBO/2016/entry. 

What I am having trouble with is when I call up the entries in the admin dashboard/competition status/entry counts/counts by style, or (http://www.clarksvillecarboys.com/NSBO/2016/index.php?section=admin&go=count_by_style), but you can't see that without admin privileges obviously,  the software is calling up information relative to the BJCP 2015 guidelines and not what I have edited in the database. I figure that this information is stored elsewhere but I can't seem to find it. Can you help me? 

Cheers,

John Lawless
NSBO Judge Coordinator/Webmaster

**Comment by geoffhumphrey** [comment]
If you've modified the styles directly in the DB, this will, indeed, break not only the count by style and count by substyle displays, but will also break the jquery functions when users are adding an entry that check whether that style requires special ingredients since the coding relies on the BJCP2008 or BJCP2015 defined style/substyle combinations. 

In short, at the very least, you'll need to significantly alter the programming that references the style number/substyle letter combinations in the following scripts to conform to your new schema:
- /admin/entries_by_style.admin.php
- /admin/entries_by_substyle.admin.php
- /sections/brew.sec.php

**Comment by jlawless1** [comment]
Thanks. I've been looking over 
> /admin/entries_by_style.admin.php
> /admin/entries_by_substyle.admin.php
But not,
> /sections/brew.sec.php
Do you mind if I email you with questions? Also I noticed the bug reporting section on github but is there a forum for discussion?

Respectfully,

John P. Lawless II
931-249-6938

**Comment by geoffhumphrey** [comment]
No problem. I sent an email to you directly just now that you can reply to...

**Comment by jlawless1** [comment]
So I have been looking over the code in these files and they seem to reference the db that stores the data "styles." The software is calling up the information that I have edited in the db and it is working correctly without changing any code here - http://www.clarksvillecarboys.com/NSBO/2016/entry. The only information that I edited in the db was numbers and letters to reflect what you see on that page.

What I don't understand is when I am in the admin section and look at the entries by style the information that is displayed references the original 2015 guidelines with all of the program native information. It would seem this data is stored elsewhere but I can't seem to figure out where. http://www.clarksvillecarboys.com/NSBO/2016/index.php?section=admin&go=count_by_style
