### ISSUE TITLE
Paypal payments off by $0.01

### ISSUE THREAD

**Issue by PeterSteinberg** [geoffhumphrey/brewcompetitiononlineentry#602]
I've got my competition set up to take paypal and for the entrant to pay the paypal fees.

Almost all the payments I receive are off by a penny; i.e. I should receive $7.00 after paypal fees but I only receive $6.99

**Comment by geoffhumphrey** [comment]
Peter, this has been an on again / off again issue since the first release. Sometimes it's right on the money (so to speak) and other times it's not. The calculation formula is straight off of PayPal's terms of use - 3% of price plus $0.30 fee. The amount is rounded up as well. Seems to be an issue on the PayPal side of things... What might be the easiest solution is to simply add a penny to the calculated amount before it's sent on to PayPal.

**Comment by geoffhumphrey** [comment]
To add the penny to the total, change lines 133-135 (2.1.0 release) in the /sections/pay.sec.php file to be:
```
$fee = number_format((($total_to_pay * .03) + .30), 2, '.', '') + .01;
if ($_SESSION['prefsTransFee'] == "Y") $payment_amount = $total_to_pay + $fee; 
else $payment_amount = number_format($total_to_pay, 2);
```

**Comment by PeterSteinberg** [comment]
We're still hosted by you so I can't change the code...

**Comment by geoffhumphrey** [comment]
I'll be updating hosted accounts to 2.1.0 in the coming week. Should be able to work in this code too...

**Comment by PeterSteinberg** [comment]
Thanks.

Peter
