### ISSUE TITLE
Cannot change "Use Queued Judging" via the website

### ISSUE THREAD

**Issue by Zvish** [geoffhumphrey/brewcompetitiononlineentry#618]
Hi,
I tried to change the field "Use Queued Judging" under Admin-> Preferences -> Competition Organization.
When applying the change it is not getting changed in the DB.
Zvi

**Comment by geoffhumphrey** [comment]
This should be fixed with an upgrade to 2.1.2. If not, run this SQL command in your DB (remember to prepend your prefix if you have one defined in config.php):
```
ALTER TABLE `judging_preferences` CHANGE `jPrefsQueued` `jPrefsQueued` CHAR(1) NULL DEFAULT NULL;
```
After that setting is changed in the DB, log back into the site and go to Preferences > Competition Organization. Choose whether you want queued judging or not.

**Comment by Zvish** [comment]
I am on 2.1.2 and it's not working.
I ran the command and it's good now on the GUI as will.

**Comment by Zvish** [comment]
Issue resolved
