### ISSUE TITLE
full screen browser cutting off page

### ISSUE THREAD

**Issue by chintoopatel** [geoffhumphrey/brewcompetitiononlineentry#640]
#When browser(chrome) is maximized/full screen, some of the pages are getting cut off causing submit buttons for forms to be hidden.

example page : Edit Account

v2.1.4

**Comment by geoffhumphrey** [comment]
Thanks for reporting. Please provide some more information: browser and version (mobile or desktop), etc. Screenshots would be helpful as well. 

More than likely, this has to do with the site theme not being loaded; this will cause the buttons not to be visible on some pages in full screen view, like this (Edit Account):
![screen shot 2016-07-08 at 7 29 37 am](https://cloud.githubusercontent.com/assets/5216502/16688950/c0f1c37a-44dd-11e6-8427-5302241a28e6.png)


The Edit Account page looks like this when the chosen theme is loaded (Mac running Chrome 51.0.2704.103):
![screen shot 2016-07-08 at 7 31 37 am](https://cloud.githubusercontent.com/assets/5216502/16689010/0946f3fc-44de-11e6-9f39-536b4e4e216f.png)


To check if the theme is being loaded, right-click on the page and select "View Source" - on or around line 45 should read:
```
<link rel="stylesheet" type="text/css" href="http://test.brewcomp.com/css/default.min.css" />
```
or
```
<link rel="stylesheet" type="text/css" href="http://test.brewcomp.com/css/bruxellensis.min.css" />
```
or
```
<link rel="stylesheet" type="text/css" href="http://test.brewcomp.com/css/claussenii.min.css" />
```
If that line doesn't look like one of the above, your theme isn't loading.

If the theme isn't loading, chances are your preferences are not being recognized from the DB. To set your preferences, do the following:

1.  Log in as an Admin and go to Preferences > Website Preferences. 
2. Choose a Site Theme. 
3. Tab or click through so that your cursor is in a text field, then hit Return. 

If that doesn't work, the next step is to access the DB directly. If that's the case, I'll walk you through it.
