### ISSUE TITLE
Error during upgrade - Duplicate column name 'sponsorLevel'

### ISSUE THREAD

**Issue by jqoutlaw** [geoffhumphrey/brewcompetitiononlineentry#647]
Hello,
I am going from 1.2.0.4 to 2.1.4 and receiving an error when run the upgrade script - Duplicate column name 'sponsorLevel' 

I was wondering if my upgrade path is to far apart. 

Thanks

**Comment by geoffhumphrey** [comment]
@jqoutlaw, there should not be any hang-ups when upgrading from 1.2.0.4 to 2.1.4. Unfortunately, I cannot track down where this problem is potentially happening in the code (there's only one place in the update scripts where 'sponsorLevel' is specified, but it's part of code to upgrade from an earlier version than yours, and thus not included). I'll be doing some testing later today to try and track down the offending code.

**Comment by jqoutlaw** [comment]
The only other thing I can think of is there are several archive competitions. I have multiple sponsor tables with the archive name appended like below:

| sponsors                              |
| sponsors_2014                         |
| sponsors_BonaFide2013                 |
| sponsors_Jacktoberfest2013            |
| sponsors_Jacktoberfest2014            |
| sponsors_Jacktoberfest2015            |
| sponsors_MonsterMash2012

**Comment by geoffhumphrey** [comment]
Give this a try for now... In the downloaded 2.1.4 package, locate the /includes/version.inc.php file. Edit the $version variable to be:
```
$version = "1.2.0.4";
```
Upload it to your site's /root/includes/ folder and then try to run the update again. I just tested it and it worked for me.

**Comment by jqoutlaw** [comment]
That worked Geoff. Thanks for the help on this one.

**Comment by geoffhumphrey** [comment]
I've updated the [upgrade instructions](http://brewcompetition.com/upgrade-instructions) to incorporate this work-around.
