### ISSUE TITLE
urgent - judging stickers not showing prefixes

### ISSUE THREAD

**Issue by rgiaquinta** [geoffhumphrey/brewcompetitiononlineentry#651]
Sorry... I don't have time to research this issue, as my sort is tonight and my job needs me this afternoon.   I have regenerated judging numbers and am about to print out bottle stickers and pull sheets.   The judging numbers are not the usual format (ie subcategory prefix - 001 etc).  Instead, they are just random 6 digit numbers that will make it take FOREVER to put onto bottles.  You have any idea what the issue is?  I need to get this worked out by tonight.... thanks in advance for your help!

**Comment by geoffhumphrey** [comment]
The random numbers were introduced in version 2.1.1 due to the numerous issues encountered by the  previous system of prepending the subcategory. However, note that when you print out bottle labels, the category and subcategory are present with the judging number in ascending order:

Avery 5160
![screen shot 2016-07-21 at 10 15 04 am](https://cloud.githubusercontent.com/assets/5216502/17030287/181cbe7c-4f2c-11e6-8874-ea48aa90ffc0.png)
Round Bottle Labels
![screen shot 2016-07-21 at 10 15 38 am](https://cloud.githubusercontent.com/assets/5216502/17030303/26637bf6-4f2c-11e6-98b7-3d9fc5452edd.png)

Use of these in conjunction with the Sorting Sheets and the Entry Number/Judging Number Cheat Sheets should not increase the time it takes to sort. I have not had anyone using the software since the random numbers were introduced let me know that sorting took longer than any previous occurrence. Please let me know if it does for you.

**Comment by rgiaquinta** [comment]
Thanks for your quick reply.  The sort went fine.  I did not notice that the labels had the cat/subcat on them; I only saw that the cheat sheets did not have the usual prefix and -001 organization and I freaked out b/c it was different than I had seen in previous years.  Thanks as always for your valiant work with this software.  One thing I did notice is that the cheat sheet does not organize by subcategory (ie. on the cheat sheet, a 1B beer might be listed before a 1A beer, but I'll have time to do my due diligence troubleshooting before asking you any questions about this....

**Comment by geoffhumphrey** [comment]
Some other comp organizers were lamenting the decision to go to random judging numbers as well, preferring the "old" way of generating judging numbers that had the style number prepended. The next version will give administrators the opportunity to "regenerate" judging numbers to utilize the old schema.

This will only be for regeneration. Entries added to the DB will continue to be assigned a random judging number. Therefore, if admins wish to have all judging numbers utilize the legacy methodology, they should only perform the regeneration after all entries have been added to the system.

**Comment by rgiaquinta** [comment]
Having just completed our 340 entry competition this weekend, I feel that the randomized numbers are superior to the 01-001 format because they make it less likely for sorters/pullers/scorers to get into a consecutive number rhythm and stop looking carefully at the actual printed numbers.  I also agree that the randomized numbers do not add a significant amount of time to sorting/pulling/scoring etc.  We had a few cases where handwritten numbers were transposed, and when I doublechecked the number in the system, the 6 digit random number assured me that the transposed number could only refer to one particular entry, because there was no other 6 digit number that was even close.  This would not be as simple if there was confusion between 01-012 and 01-021.
