### ISSUE TITLE
Enhancement Requests: Keg Competitions

### ISSUE THREAD

**Issue by BearcatBrewmeister** [geoffhumphrey/brewcompetitiononlineentry#653]
We run a keg competition and know a few others that do so as well (entries are corny kegs instead of bottles).  It would be nice if the two following options existed to support this type of competition:

- All the hard coded spots with shipping info: since kegs need to be set up by the entrant, there is no shipping allowed.  In the current version, we have to note in many places to ignore the shipping instructions, but every year we get contacted about shipping (even though we set the shipping address as None - Hand Carry only).  It would be great if we could have a set up option for no shipping that removes all the mentions of shipping such as the required address entry and the postal shipping instructions (USPS illegal, etc.).
- Judging numbers: instead of auto-generating, we would like to manually assign them.  An entrant may enter multiple kegs at different times during the registration window and the competition staff needs to consolidate the entries for a person adjacent to each other or front to back to facilitate the CO2 hookup.  The tap hook ups are numbered in increasing order around the room in rows so an entrant can find out where to place his entries and so that the steward can find the entries he needs to pull a sample from for his flight.  We would like to manually assign the judge number as the tap number so it feeds into the pull sheet.  As it stands, we have to export to HCCP and use HCCP from pull sheet generation to the end of the competition.

There are other minor things, such as the word bottle being subbed out for keg, but those are minor compared to the two main items listed above.

Thanks for everything you do - Cheers!

**Comment by geoffhumphrey** [comment]
@BearcatBrewmeister, thanks for your suggestions. I'll give them some consideration as to their impact.

With regard to the first bullet, it may be as simple as a toggle in preferences to enable/disable shipping information display.

With regard to the second bullet, Admins have the ability in the current version (actually since 2.0.0) to assign judging number manually via the Admin > Entries and Participants > Manage Entries screen:
![screen shot 2016-08-01 at 8 55 11 am](https://cloud.githubusercontent.com/assets/5216502/17298071/b86c4374-57c5-11e6-981b-b2a04a49155e.png)

Enter the desired judging number and then hit the Update Entries button at the bottom of the page.

The system will always automatically generate a judging number, you can manually change it via this screen or using the [barcode/QR code entry check-in functions](http://brewcompetition.com/barcode-check-in).

Cheers to you!

**Comment by BearcatBrewmeister** [comment]
Thanks for the consideration.  My apologies on missing the judging number assignment.  I manually changed one and didn’t see it update, but I believe I forgot to hit Update Entries because I tried again and it works perfectly.
