### ISSUE TITLE
Access Archived Score Sheets / Entries

### ISSUE THREAD

**Issue by elronalds** [geoffhumphrey/brewcompetitiononlineentry#655]
When we archive a competition it would be nice to retain the entries and scoresheet data so a registered entrants could access their entry history and download old score sheets.

Entrants can use the same accounts for future competitions so it makes sense to allow them to access all their old data.

**Comment by geoffhumphrey** [comment]
Seems reasonable. I'll put it on the enhancements list. Coding that assigns judging numbers would have to be extended to cover all archives as well since the function relies on matching the entry judging number with a document that has the same number as its name in the user_docs folder. In other words, past and future judging numbers must be wholly unique.
