### ISSUE TITLE
BOS Pullsheet need an option to print by entry number

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#670]
Right now it looks like those can only be printed with judging numbers, so I'm using the placemat for the stewards to pull (we used entry numbers for this competition). Luckily it's only an eight-entry BOS.

(As an aside, why the six-digit judging numbers? I judged a comp yesterday using them, and it's kinda cumbersome to deal with these long numbers that aren't immediately "recognizable". IMO it would be good to have an option to simply use sequential numbers starting with 0001, just different from the entry number.)

**Comment by geoffhumphrey** [comment]
Hrm. Looks like you have stumbled across a function that was there in previous versions prior to 2.0, but was omitted in the UI conversion of that release. The functionality is there, but there's not an intuitive or direct method to be able to print a pull sheet with entry numbers instead of judging numbers. The most direct path would be to right-click on the BOS pull sheet of choice from the Admin Dashboard > Reports menu, and choose to open the link in a new tab or window (this bypasses the modal load of the report). Then, it's simply a matter of adding ```&view=entry``` to the end of the URL and hitting enter to load.

Something like this:
```
[BaseURL]/output/print.output.php?section=pullsheets&go=judging_scores_bos&view=entry
```

I'll get a proper link back on the admin dashboard in the next version, due out in a couple of days.

With regard to the six digit judging numbers, those sprang forth from my involvement in updating the software for use by the AHA for the National Homebrew Competition. One of the requirements was to have judging numbers that could have no possible way of identification. Since that's a pretty big number of entries, six digit judging numbers seemed to be the best approach since they used to be a two digit prefix that was the style number (e.g., 02 or 23) and a four digit unique judging number. I've taken that a bit further in recent releases to make sure judging numbers are completely random. See the thread in Issue #651 for one organizer's opinion of the randomized six-digit judging numbers.

For a future release, an option for Admins could be to provide a choice of how long their judging numbers could be. The function that is used to generate the numbers has this built in flexibility. I would probably start at 4 and end at 10.
