### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by KarlWeiss** [geoffhumphrey/brewcompetitiononlineentry#674]
I am getting an error that is causing my install not to load. "Too many redirects occurred trying to open..." I tried updating from 2.1.5 to 2.1.6 and was able to successfully update but then got the same error. Perhaps I am just missing something but I need to solve this issue to get the page to load.

**Comment by KarlWeiss** [comment]
I believe I fixed the issue. The very first beer of the competition was entered and it had an "&" in the beer name. That created the redirect issue. I deleted that entry and the software now loads.

**Comment by KarlWeiss** [comment]
I am now getting the redirect issue again. This time I am getting for following error as well: "User 'my database user name' has exceeded the 'max_questions' resource (current value: 75000)"

**Comment by geoffhumphrey** [comment]
Not sure why this is happening, but I it has to do with an automated process that checks to see if any entries do not have associated judging numbers. 

First, are you running the latest version, 2.1.6? If not, please update your site to 2.1.6.

If so, I would first delete all files off your your server and reinstall them. Don't overwrite them. This has worked for me in the past.

If you're still having this issue, you'll need to disable a couple of automatic processes that run on each page load. Open /site/bootstrap.php. Look for the section called Data Integrity Checks. It will look like this:

```
// ---------------------------- Data Integrity Checks ---------------------------- 
	
// Perform data integrity check on users, brewer, and brewing tables at 24 hour intervals
if ((isset($_SESSION['dataCheck'.$prefix_session])) && ((isset($_SESSION['prefsAutoPurge'])) && ($_SESSION['prefsAutoPurge'] == 1))) {
	if ((!NHC) && ($today > ($_SESSION['dataCheck'.$prefix_session] + 86400))) data_integrity_check();
}
	
// check to see if all judging numbers have been generated. If not, generate
if ((!check_judging_numbers()) && (!NHC)) header("Location: includes/process.inc.php?action=generate_judging_numbers&go=hidden");
	
// Check if judging flights are up-to-date
//if (!check_judging_flights()) $check_judging_flights = TRUE;
//else $check_judging_flights = FALSE;
	
$check_judging_flights = FALSE;
```
Comment out the third "if" statement (put two forward slashes in front of it). It should look like this:
```
// check to see if all judging numbers have been generated. If not, generate
// if ((!check_judging_numbers()) && (!NHC)) header("Location: includes/process.inc.php?action=generate_judging_numbers&go=hidden");
```
Finally, since the check for judging numbers isn't being run automatically, you'll need to keep an eye on them as you gather entries. Use the Regenerate Judging Numbers function from the Admin Dashboard just before sorting to make sure all entries have them.

**Comment by KarlWeiss** [comment]
Commenting out the third if statement solved the problem! Thanks Geoff.

**Comment by dogunter** [comment]
I had this same issue (running 2.16). I uncommented the "if" test as you suggested and my site works again. However, I tried to regenerate the judging numbers and now they are all set to NULL.

Any ideas on how to regenerate numbers?

**Comment by geoffhumphrey** [comment]
Ah, I see the problem! There are two places for admins to regenerate judging numbers: 

1. On the Admin: Entries page that lists all entries. It's accessed from the "Admin Actions" dropdown.
2. On the Admin Dashboard under the Entry Sorting heading.

It's the one from the Admin: Entries page that isn't generating the judging numbers, resulting in what @dogunter described above. We have a bug!

@dogunter, if you start the regeneration process from the Admin Dashboard, judging numbers will be restored. 

I'm going to open another issue report detailing the bug on from the Admin: Entries page.
