### ISSUE TITLE
Dry Mead - Strength & Carbonation Options Not Present

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#680]
This is a very specific situation. I'm running a mead-only competition, and therefore when setting up a new entry M1A is the default style shown. Unless you select a different style and then go back to M1A the additional information fields for strength and carbonation do not appear.

I suspect for any competition that also includes beer or cider this will not be an issue as the default style will be something else, and anyone entering a Dry Mead will have to select it from the dropdown thereby enabling the options. But in this case, the software is not recognizing that it needs to provide those until you select a different mead style and then go back.

BCOEMS 2.1.4 / OS X 10.9.5 / Chrome

**Comment by geoffhumphrey** [comment]
Confirmed in 2.1.7. Will post a fix after testing has confirmed new functionality.

**Comment by geoffhumphrey** [comment]
Fix is in the latest commit. Basically, instead of the dropdown defaulting to the first style that's available on the list, it has no default; instead the user is prompted to "choose a style." Thus, like in the situation @BrewDrinkRepeat describes above, the first style in the dropdown list is not selected by default and the jquery scripting enforcing required information will be implemented.

If no style is chosen, the entry will not be confirmed in the DB. That's the only drawback to this approach. A more elegant solution involving jquery may be needed in the future.
