### ISSUE TITLE
"Update Entries" not working

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#682]
I have been going through the list of entries in my competition today and updating rec'd status after sorting day. I made it through over 500 entries before all of us a sudden the update entries button stopped working. Now it refreshes the page like usual, shows the red pop-up saying it worked, but then I scroll down the checkmark I added wasn't saved...

Please help...

**Comment by geoffhumphrey** [comment]
Unfortunately, in the six years that this functionality has been a part of the codebase, I've never had this bug surface before. I'm not able to replicate it on any of my test installations, local or otherwise. I've looked at the code and it should update as expected - it uses a simple loop in php to update each record according to the user's input. Recall that there is text beneath the Update Entries button that states, "Click 'Update Entries' before paging through records."

Given that, my advice would be to download the latest codebase and re-upload to your installation, replacing all of the files. Clearing your browser's cache and cookies couldn't hurt either.

There may be an outside chance that you have exceeded your hosting provider's limit of DB queries (most hosting providers do), but that number is usually in the 50-75,000 per day range. This applies mostly shared hosting plans.

Apologies, I wish I had a quick and elegant solution, but the code is working as expected in the environments I use to test.

**Comment by ercousin** [comment]
I managed to get it working again, after some playing around, I cut the # of entries to display at a time back to 400 from 1000 (702 entries registered). It seems to be working now.

Perhaps it was a host related issue with a query quota (I'm on Siteground GrowBig plan), since it was working for the first 2/3 of the entries.

**Comment by geoffhumphrey** [comment]
This is good to know for anyone having similar issues. The programming doesn't account for any specific server related quotas... It just does it's thing for every record on the screen that is part of the form submission. Glad things are working for you now.

**Comment by ercousin** [comment]
Thanks for the great support as always @geoffhumphrey !

Our big annual competition is judging this weekend, so I may be posting again if I run into any unexpected issues.

I'm still on 2.1.5 since I'm too scared to run the update database script when I have 702 entries and 230 participants in the system.
