### ISSUE TITLE
Confirmed Entry Count

### ISSUE THREAD

**Issue by michaeltrego** [geoffhumphrey/brewcompetitiononlineentry#683]
The Admin Dashboard shows a confirmed entry count of 440, but when I drill into the entries detail there are 466 entries.  Why the difference?

**Comment by geoffhumphrey** [comment]
With just the info you've provided here, 440 is the count of entries that have been confirmed with 26 "unconfirmed" - do you see 26 unconfirmed entries on the Admin Dashboard and when you go to the entries list via Admin > Entries and Participants? 

If not, there I'll have to investigate further...

**Comment by michaeltrego** [comment]
Unconfirmed Entries on the dashboard shows zero.

**Comment by geoffhumphrey** [comment]
OK. Unfortunately, I'm not able to replicate.

What version are you using? In the latest version (2.1.7), I'm getting the correct count on the Admin Dashboard and the unconfirmed entries are flagged as such on the Admin > Entries and Participants > Manage Entries.

**Comment by michaeltrego** [comment]
We are on hosted 2.1.7 -- http://nerhbc.brewcomp.com/
Screenshots attached:
![entries](https://cloud.githubusercontent.com/assets/22302281/18962664/c51ca08e-863f-11e6-86b9-8b499466e179.png)
![counts](https://cloud.githubusercontent.com/assets/22302281/18962665/c51d2a4a-863f-11e6-8671-28d9349b4c16.png)

**Comment by geoffhumphrey** [comment]
The numbers look correct to me - 404 paid confirmed + 36 unpaid confirmed =  440 total confirmed entries.

The 466 is simply a number generated by MySQL based upon the last id number used (in MySQL speak it's called the Primary Key - these id numbers generated by MySQL serve as entry numbers in the BCOE&M codebase). It doesn't necessarily indicate the total number of records since some entries in the DB (26 in this case) were deleted along the way. 

If you sort by entry number in your installation, you'll see some gaps in the entry number sequence - for example, entry numbers 0071 and 0091 are missing. That indicates they were deleted from the DB at sometime in the past.

**Comment by michaeltrego** [comment]
Ah - that's explains it - thanks very much for the quick replies Geoff.
