### ISSUE TITLE
Print Bottle Labels (All Entries) is not printing all info

### ISSUE THREAD

**Issue by BrewDrinkRepeat** [geoffhumphrey/brewcompetitiononlineentry#684]
I'm currently running a mead-only competition, so every entry has some additional info (strength, carbonation, sweetness) in addition to honey variety, special ingredients, etc.

I'd like to print these labels for the judges to use on the scoresheets (to avoid having to transfer all of the info from the pullsheet), but the standard categories (M1A/B/C, etc.) are not printing the strength, carbonation level or sweetness on the labels, or any other info entered such as honey variety.

Those characteristics _are_ included on the labels where special ingredients are printing.

Not sure if this is a bug report or a feature request, depending on the original intent of this option, but IMO all of that information should print on all labels.

Thanks!

v2.1.4
OS X
Chrome

**Comment by geoffhumphrey** [comment]
There was an issue with the /output/labels.output.php file where the strength, carb, and sweetness were not showing up for mead and cider styles that did not require special ingredients (e.g., Dry Mead, etc.). That has since been fixed in the latest commit. See below...

![screen shot 2016-10-03 at 1 10 27 pm (https://cloud.githubusercontent.com/assets/5216502/19050214/e1d422a0-896a-11e6-8666-f4831530fe61.png)


You can also generate labels "With Required Info - All Categories" that will detail carbonation, strength, and sweetness where required. These are available using Judging Numbers or Entry Numbers and can be accessed on the Admin Dashboard's Entry Sorting menu.

The general bottle labels (either Avery 5160 or Avery 3422) that have 6 numbers per label do not have this information because those are meant to be sliced and diced manually for application on bottles.
