### ISSUE TITLE
Support for Single Bottle Tracking

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#685]
I have a kind of feature request.

I'm not sure how common this is for other competitions, but sometimes single bottles arrive (even when we require two). Breakage or not caring about BOS are usually the causes.

I'm not sure about the exact logic but it would be extremely handy if there were a way to track these entries that only have one bottle on the pullsheets and other print outs and databases. Currently we have to track them on our own spreadsheet.

These single bottles really wreaked havoc on our cellar master in our recent 700 entry comp because it was hard to track. We printed extra pullsheets for him to use for sorting, and they didn't really notify him which were singles....

Thanks,
Eric

**Comment by geoffhumphrey** [comment]
The way we accomplished this in our last comp was to put the "Brewer's Specifics" field to work for us. After sorting I went into the system and flagged all of the entries with a single bottle as such by editing its entry record. This guaranteed that the information would show on the pull sheet to alert stewards and judges...

**Comment by ercousin** [comment]
That's a clever solution, but it would still be handy to have official support for tracking single bottles. Would make our cellar master's job much easier.

Perhaps even just some cellar master specific print outs, instead of using pullsheets.

**Comment by geoffhumphrey** [comment]
Eric, if you have any suggestions as to what data the cellarmaster specific printouts would show, please let me know.

**Comment by BrewDrinkRepeat** [comment]
What I normally do is put "SB" in the box location field. That way it shows up on the pullsheets and both the judges and stewards know that this is a single-bottle entry. 

We don't use any separate printouts for cellarmasters or stewards; we organize the bottles during the sorting (usually by category or table, if we already know the table breakdowns, rather than numerically so the stewards can get all of the bottles for a particular table in one place) so the pullsheets are all they need.

**Comment by geoffhumphrey** [comment]
In the 2.1.13 release there was a field added with single bottles in mind. See issue #871.
