### ISSUE TITLE
BJCP Judging Points Report Seems Wrong

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#690]
My understanding is that judges earn up to 1.5 pts per day at a rate of 0.5/flight, but I had some judges that did 4 flights in one day show up as 2 pts.

Also it seems to exclude BOS from the points calculation for certain people randomly.

Example 1:
Fri: 3 flights
Sat: 4 flights
Sun: 4 flights + BOS (beer)
Weds: 1 flight (cider)

This should all add up to 5 pts, but it shows up as 4.5

Example 2:
Fri: 2 flights
Sat: 4 flights
Sun: 4 flights + BOS

BCOEM correctly calculates this as 4.5

Example 3:
Saturday: 4 flights

This should calculate to 1.5 pts due to the daily max, but shows as 2.0

**Comment by geoffhumphrey** [comment]
Thanks for reporting. I'll recreate what you've detailed and look into the calculation codes to see what logic is amiss. Stay tuned.

**Comment by geoffhumphrey** [comment]
Just to clear things up after re-reading your post. The BJCP awards 0.5 points per **session** not per **flight**.

According to the [BJCP's Competition Handbook](http://www.bjcp.org/docs/SCPCompHdbk.pdf), a session is (p. 13):

> An uninterrupted time period when at least one panel of judges sits to judge **one
or more flights** of entries. Typically, morning, afternoon and evening are considered sessions
at most competitions.

Further, a flight is defined as (p. 13):
> A single grouping of entries that are combined for the purposes of judging, that are
evaluated by a single panel of judges, and that result in a ranked ordering for purposes of
determining awards. In large competitions, a single category may be divided into multiple
flights with the overall winner determined in a Mini-BOS round.

For the purposes of the calculation in BCOE&M, sessions (or rounds) are counted, not individual flights, since a "recommended flight" consists of 10 entries with a maximum allotted time of 2.5 hours and will typically consume the total time of a "session." Again, this is derived from the information in the competition handbook.

Still, this does not account for the calcs you reported, just something to keep in mind.

**Comment by ercousin** [comment]
Closed issue since this issue seems fixed in 2.1.14
