### ISSUE TITLE
Historic beers category only shows 27A 

### ISSUE THREAD

**Issue by brices121** [geoffhumphrey/brewcompetitiononlineentry#700]
The Historic beer only shows up as 27A the remaining us categories do not show up.

**Comment by geoffhumphrey** [comment]
Historic Beers in the BJCP guidelines is the category and since it does not have any defined sub-styles, the category name is only represented. The examples in the BJCP 2015 style guidelines are not sub-styles, they are examples identified by the BJCP that are not exhaustive (in their determination) . Because these examples are not defined as sub-styles, they are not reflected as such in BCOE&M.

There are clear entry guidelines provided by the BJCP that are enforced by BCOE&M to the extent of its programming - users are required to enter additional information in the Required Info field:

> The entrant MUST either specify a style with a BJCP-supplied description, or provide a similar description for the judges of a different style. If a beer is entered with just a style name and no description, it is very unlikely that judges will understand how to judge it. Currently defined examples: Gose, Piwo Grodziskie, Lichtenhainer, Roggenbier, Sahti, Kentucky Common, Pre-Prohibition Lager, Pre-Prohibition Porter, London Brown Ale.

**Comment by brices121** [comment]
Thanks

**Comment by geoffhumphrey** [comment]
In the next release, the BJCP defined examples in both Specialty IPA (21B) and Historical Beers (27A) will be their own salient "sub-categories" - even though they are not defined as such by the BJCP (e.g., they do not have a sub-category letter). So, essentially, these will be "sub-sub-categories." 

This will provide admins the flexibility to assign these "sub-sub-categories" to tables individually so that their associated entries can be judged with similar sub-categories. Therefore, if so desired, Piwo Grodziskie entries can be judged with other smoked beer entries, Belgian IPA can be judged with other Belgian-style entries, Pre-Prohibition Lager can be judged with other American-style lagers, etc.

Anyway, they will be...

**21B Specialty IPA** (now becomes a catch-all for non-defined specialty beers such as Black Rye IPA, Belgian Black IPA, etc.)
- 21B1 Belgian IPA
- 21B2 Black IPA
- 21B3 Brown IPA
- 21B4 Red IPA
- 21B5 Rye IPA
- 21B6 White IPA

_All of the Specialty IPAs require strength to be defined as session, standard, or double._

**27A Historical Beer** (now becomes a catch-all for non-defined historical beers like Adambier, etc.)
- 27A1 Gose
- 27A2 Piwo Grodziskie
- 27A3 Lichtenhainer
- 27A4 Roggenbier
- 27A5 Sahti
- 27A6 Kentucky Common
- 27A7 Pre-Prohibition Lager

**Comment by brices121** [comment]
Cool,

I do have another question or comment. Scheduling didn't quite work the way
I expected. I had a problem scheduling judges for not then one session in a
day. For instance I had two sessions on Thursday and Friday but I was
unable to assign a judge for both sessions. Are there directions on how to
do this or is it a limitation of the software?

Brice
