### ISSUE TITLE
Localization: YYYY/MM/DD date format does not work correctly

### ISSUE THREAD

**Issue by kstec** [geoffhumphrey/brewcompetitiononlineentry#702]
What I have for Website Preferences:

![image](https://cloud.githubusercontent.com/assets/216067/20447741/22d0adaa-ada6-11e6-9b65-7e359208ee6d.png)

What I see on the Home page:
![image](https://cloud.githubusercontent.com/assets/216067/20447730/142f0c10-ada6-11e6-99f3-bcd58fa71947.png)

**Comment by geoffhumphrey** [comment]
Confirmed. The fix is very simple.

For version 2.1.7, edit line 94 in the /lib/date_time.lib.php file to read:
```
elseif ($date_format == "2") $date = date('d/m/Y',$timestamp);
```
There was a missing equals sign in the operator that was not allowing the "else" statement on the next line to be executed. That "else" statement is what would correctly format dates in your chosen format.

**Comment by kstec** [comment]
Thanks!
