### ISSUE TITLE
Upload Scoresheets By Entry Number (PDF)

### ISSUE THREAD

**Issue by jimpdx** [geoffhumphrey/brewcompetitiononlineentry#731]
We do not use Judging numbers in our competitions. Would it be possible to allow site admins to upload by ENTRY or JUDGING number (000023.pdf or similar)? Thank you.

**Comment by geoffhumphrey** [comment]
This would require a bit of a code change, which turns out to be pretty easy to implement. Download the attached zip and upload the files within it to your installation:
- Upload the brewer_entries.sec.php file to the /sections/ directory
- Upload the scoresheets.output.php file to the /output/ directory

This will apply to version 2.1.5 and later. Please give it whirl and report back.

This code will be integrated into the next release.

[scoresheets_download_update_2017.02.03.zip](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/751130/scoresheets_download_update_2017.02.03.zip)

**Comment by geoffhumphrey** [comment]
Please note that for the download to function properly, the PDF file name must be 6 digits with leading zeroes (e.g., entry number 0329 would be 000329.pdf).

**Comment by jimpdx** [comment]
Thanks you @geoffhumphrey! That was quick :) We will make this change on [shebrew.oregonbrewcrew.org](url) and use it later this month. Will let you know if we have any issues.

**Comment by jimpdx** [comment]
@geoffhumphrey I applied the change to a 2.1.7 site I had from last Fall. The bulk file upload failed when I added a few scoresheets (possibly permissions) but the single file upload worked. And the scoresheets were visible on "My Entries" so it works great. Might want to modify the Scoresheet upload page as it still says "only judging numbers". Thanks again for the quick update!

**Comment by geoffhumphrey** [comment]
The bulk upload function worked for me on my test servers. May want to check your permissions.

Will do about modifying the nomenclature on the upload page. I'll be making a commit soon with all of the changes. The updated code will also have enhancements that obfuscate the file names in the URL to prevent users from accessing files on the directory they shouldn't.
