### ISSUE TITLE
Forgot/reset password process is insecure

### ISSUE THREAD

**Issue by gene1wood** [geoffhumphrey/brewcompetitiononlineentry#740]
[Text removed by admin due to sensitive nature]

**Comment by geoffhumphrey** [comment]
Gene, thank you for the insight here. In the interest of not having all sorts of attacks happen to sites across the internet, I'll be removing your text here and saving it locally for review and remedy. I think you can understand that such a detailed use, especially since you call out Derrick Shular specifically, is not in the best interest of this community.

**Comment by geoffhumphrey** [comment]
For 2.1.10, 22 newer and "stronger" questions will be incorporated for security verification to replace the current set of four. In a future release, a token system is planned to be put into place.

**Comment by geoffhumphrey** [comment]
See issue #788 for further clarification.
