### ISSUE TITLE
Pay pal not updating some paid users

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#746]
Not exactly sure why, but a good amount of users don't get updated when the pay with paypal. Not sure how to replicate, but might be good to look at. Thanks

**Comment by geoffhumphrey** [comment]
Unfortunately, this has been a recurring problem due to the reliance upon human intervention - the current PayPal setup requires entrants to click a "return to..." link upon completion of their PayPal transaction. Sometimes they do, sometimes they don't (despite the rather in-your-face warnings). If they don't click this link, the entries they just paid for will not be marked as paid in the system, thus requiring an admin to mark these entries as paid upon confirmation of payment.

Unfortunately, there isn't a way around this at present. A future release may leverage PayPal's Instant Payment Notification service to eliminate the human intervention, but this method has some requirements that may not be possible for some users and some environments.
