### ISSUE TITLE
End competition button

### ISSUE THREAD

**Issue by torreyj** [geoffhumphrey/brewcompetitiononlineentry#756]
It would be nice to have a show scores now or end competition button

**Comment by geoffhumphrey** [comment]
A "Publish Results Now" button will be added to the Administration Dashboard. This will override two Site Preferences so that results can be posted immediately. The function will enable Winner Display and set the Winner Display Delay to 0. 

![screen shot 2017-07-03 at 9 49 24 am](https://user-images.githubusercontent.com/5216502/27800105-3d5d4bb0-5fd5-11e7-9d28-86fb90263139.png)


Of course, Admins should be completely confident that all scores and results are entered accurately before utilizing the function.
