### ISSUE TITLE
Custom Style Guidelines

### ISSUE THREAD

**Issue by womball** [geoffhumphrey/brewcompetitiononlineentry#768]
Hi,

We are looking to use this software for our upcoming club and state competitions later in the year.  These are run using different style categories to those in the BJCP 2008/2015 guidelines (sample for 2017 attached).  Is there a way to customize Style Guidelines?

Thanks.
[AABC2017_CategoriesAndStylesList.pdf](https://github.com/geoffhumphrey/brewcompetitiononlineentry/files/957392/AABC2017_CategoriesAndStylesList.pdf)

**Comment by geoffhumphrey** [comment]
A quick glance at your document, it appears that the styles and categories are essentially BJCP2015, but recategorized. If that's the case, I would suggest to simply use the native BJCP2015 styles and then organize your judging tables (essentially overall categories) to mirror your overall categories. Unless I've missed something, you won't need to do any extra work.

Otherwise, there are two ways I can think of. One utilizes out-of-the-box functions available in the program, and the other involves some custom php programming and database manipulation. 

For the former, it's pretty simple, but more time consuming. You can create each of your sub categories as a "custom" style via Admin > Competition Preparation > Styles Accepted > Add. This will, however, not keep your numbering structure intact.

For the latter, your numbering system would be kept intact, but it requires knowledge of php and mySQL database operations. Essentially, you would add your each of your comp's styles to the styles DB table and customize some php programming to "recognize" you set of styles.
