### ISSUE TITLE
With CDN libraries, lists don't load. With local libraries, entry add screen is broken

### ISSUE THREAD

**Issue by diatonic** [geoffhumphrey/brewcompetitiononlineentry#774]
I'm setting up a BCOEM install for the Western Idaho Fair Amateur Beer Competition. I was experiencing the issue where lists don't render for contacts/entries/drop-off locations.

I changed to local libraries instead of CDN libraries, and now lists render, but add entry page is kind of broken. It prompts for all optional info regardless of style chosen.

Also, if I use fancybox-2.1.7, entry add page works but lists are broken.
![2017-05-22 1](https://cloud.githubusercontent.com/assets/1490527/26329310/f2586bf0-3f03-11e7-9ea8-55828d7dd2cd.png)

If I use fancybox-3.0.47, add entry page is broken but lists work. Maybe this is a clue.
![2017-05-22](https://cloud.githubusercontent.com/assets/1490527/26329312/f51d87da-3f03-11e7-97c4-881a76cc3425.png)

Help?

**Comment by geoffhumphrey** [comment]
Not entirely sure the cause of these issues, but something is interfering with the jQuery functions, especially on the add/edit entry page. Other users have reported that if an installation is accessed via a subfolder, instead of it's own domain/subdomain, may have something to do with it, and switching to one worked for their particular installation, but I cannot see a reason for it. Others have cited issues when Search Engine Friendly URLs were in enabled via preferences.

Obviously, there's something in your environment that is shutting down or conflicting with some jQuery and Javascript functions.

A good place to start would be to strip (comment) out the libraries that aren't essential for the entry gathering phase. Start with TinyMCE, and DropZone. If the problem still persists, comment out Bootstrap-Select. If the issues still persist, post back and we'll explore other options.

For Fancybox, please make sure you are using version 2.1.5. Version 3.x is a complete rewrite and has not been tested with BCOE&M.

**Comment by diatonic** [comment]
If I comment out the Fancybox section (lines 23-26) in includes/load_cdn_libraries.inc.php then the lists work, so it seems to be related to Fancybox. 

I could give you a login to my install if you wanted to take a look. I think the reason the lists work after I follow your instructions for local libraries is because it brings in an incompatible Fancybox (instructions say to use the latest which is 3.0.47).

**Comment by geoffhumphrey** [comment]
Good catch. I'll update the instructions to use a 2.1.x version of Fancybox until 3.x is integrated.

Is the add/edit entry working as expected?

**Comment by diatonic** [comment]
Also, if I leave fancybox and comment out datatables (lines 16-19) it works, but I lose datatables.

**Comment by diatonic** [comment]
Found the problem. (After digging thorugh someone else's code)

The preferences table in the database has a column 'prefsRecordPaging' which was null & causing datatables to request 0 rows... I updated the value to 20 and it works. :D

UPDATE `preferences` SET `prefsRecordPaging` = '20' WHERE `preferences`.`id` = 1;

**Comment by geoffhumphrey** [comment]
Good catch! Just to be safe in future releases, I'll add this line to the common.db.php file (around line 110):
```
if (!empty($row_prefs['prefsRecordLimit'])) $_SESSION['prefsRecordPaging'] = $row_prefs['prefsRecordPaging'];
	else $row_prefs['prefsRecordLimit'] = 100;
```
This way, a numerical value will be stored in the session, and avoiding the DataTables choke.
