### ISSUE TITLE
Issue Changing Packaging Info

### ISSUE THREAD

**Issue by WASABCOrganiser** [geoffhumphrey/brewcompetitiononlineentry#791]
<img width="259" alt="entry" src="https://user-images.githubusercontent.com/30250208/28298327-38797bd8-6ba5-11e7-959c-be407c12535f.png">

Hey All, Wondering if there's a way to chance the ATTACH TO BOTTLE w/ CLEAR PACKING TAPE? We want our participants to submit labels using rubber bands. 

We can't find were to specify this in the labelling parameter. 

Thanks

**Comment by geoffhumphrey** [comment]
Hello @WASABCOrganiser,

There are a couple of ways to change the phrase... 

First is to choose another type of bottle label. All others say to attach with a rubber band (the anonymous bottle labels that you have chosen say to attach with tape because they're intended to be affixed to the bottles throughout the sorting and judging processes).

The second way is to edit the /templates/anon-entry.html file on or about lines 58, 94, 134, and 171.

**Comment by WASABCOrganiser** [comment]
Hey Geoff,

Excellent! Thanks for your reply. I think you've convinced us to stick with the tape solution (pardon the pun). However, for future comps that gives us some flexibility. 

Thanks
Carl
