### ISSUE TITLE
Update on sites with https protocol fails

### ISSUE THREAD

**Issue by trekie86** [geoffhumphrey/brewcompetitiononlineentry#798]
My site is configured to only use https for the protocol.

The update script, when looking for the version.inc.php file only works if the url starts as `http://` ([snippet](https://github.com/geoffhumphrey/brewcompetitiononlineentry/blame/master/update.php#L48)) This needs to be dynamic based upon the site configuration like the config.php handles it.

**Comment by geoffhumphrey** [comment]
Since all the script is doing is ascertaining whether the version.inc.php file exists in the /includes/ directory,  simple solution would be to change the $filename variable to:

``$filename = INCLUDES."version.inc.php";``

This will use the server path to the /includes/ director already defined in /paths.php instead of attempting to the file name via a url.

This change will be in the next commit and version.

**Comment by trekie86** [comment]
Even better, a much simpler solution.
