### ISSUE TITLE
QR code script usage on 1.3.04 version

### ISSUE THREAD

**Issue by markpalcare** [geoffhumphrey/brewcompetitiononlineentry#803]
G'day there,

We have a highly customised version of the application which is why we haven't upgraded. How feasible would it be to try and configure the qr.php check in function?

Cheers
Mark

**Comment by geoffhumphrey** [comment]
The QR scripting is pretty much self-contained; however, it does have a few dependencies that will need to be addressed, most notably the password function that checks the value of the contestCheckInPassword that's in the contest_info table. That password is hashed for storage in the DB and checked with the PasswordHash class (not included in the 1.3.0.4 release).

The script also requires variables contained in the /lang/ folder (not included in the 1.3.0.4 release).

The file should be placed in the root folder so that the proper location of dependent scripts can be found.
