### ISSUE TITLE
PDF Scoresheet issue when using printed judging number stickers

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#817]
If you use the qr code scanning feature to receive and label your beers you will have a problem if you also upload scanned scoresheets.  Currently the code looks for scoresheets that match either the entry number or the judging number (trying entry first) 

```
        if ($show_scoresheets) {

                // Check whether scoresheet file exists, and, if so, provide li\
nk.
                $scoresheet_file_name_entry = sprintf("%06s",$entry_number).".p\
df";
                $scoresheet_file_name_judging = $judging_number.".pdf";
                $scoresheetfile_entry = USER_DOCS.$scoresheet_file_name_entry;
                $scoresheetfile_judging = USER_DOCS.$scoresheet_file_name_judging;

```
The problem is that by using the sequential judging numbers you will have judging numbers that are idential to other beers entry number.  We have entry numbers 1-470 and judging numbers from 1-424.  Thus scoresheets are wrongly matched to the entry number not the judging number.

I can think of two solutions.  

1) Change the requirement for naming the pdfs.  Use just the integer number for entry numbers and the 6 digit code for judging numbers.  This way judging number 000123 won't match entry 123.

2) Add a setting in the config file or in the competition preferences as to which format you use for the scoresheets.  Then only look for those matching sheets.

To get through our comp this weekend I am simply changing the line
```
                $scoresheet_file_name_entry = sprintf("%06s",$entry_number).".pdf";
```
to
```
                $scoresheet_file_name_entry = $entry_number.".pdf";
```
to implement option 1.  I won't be sure if this works until this evening when the scoresheets go live but I'm pretty sure this will work.

**Comment by markalston** [comment]
Just thought of a third option.  Require the pdfs names to indicate judging or entry numbers by naming them either j000001.pdf or e000001.pdf depending on what numbers you are using.

**Comment by geoffhumphrey** [comment]
The code was written to use sequential 6 digit numbers (e.g., 000001 through 999999) that either correspond to the system-generated six-digit judging numbers, the system generated entry number in six-digit form with leading zeroes, or those input via the barcode scanning procedure. This has worked for numerous comps since implementation in version 2.10. 

@markalston, your concerns are very valid, and frankly, I'm surprised they haven't surfaced sooner with regard to the QR code. The solution you provide should work for your purposes in the interim - please let us know if it didn't. 

For the next release, there will be a more robust check for the type/form of entry and judging numbers that is input for judging numbers via the QR code function, the barcode function, and the Admin > Entries function so that scoresheets will be available to entrants no matter what judging number combination is utilized (entry numbers are provided by mySQL and cannot be overridden via the application).

**Comment by geoffhumphrey** [comment]
In the latest commit and in the next release, there will be an option for Admins to prescribe via Website Preferences whether scoresheet filenames will be based upon the system-generated entry number in six-digit format or based upon the six-character judging number (judging id).

There will be instructional text with examples and a paragraph advising Admins of possible issues with using entry numbers with regard to archived data. This will be available via a modal on the Admin > Website Preferences screen:

![2017-09-21_9-10-59](https://user-images.githubusercontent.com/5216502/30703417-e676b7ca-9eac-11e7-8dd0-98bb34ad567a.jpg)

**Comment by geoffhumphrey** [comment]
Regarding archived scoresheets, a straight-forward solution for those wishing to utilize the entry number method would be to create a sub-folder in the user_docs directory that would house all of the archived scoresheets for that archive.
