### ISSUE TITLE
error in winners.sec.php

### ISSUE THREAD

**Issue by markalston** [geoffhumphrey/brewcompetitiononlineentry#821]
While the winners display is working fine, winners.sec.php is filling our logs with the following error:
```
[Mon Aug 28 15:59:48.674725 2017] [proxy_fcgi:error] [pid 5344] [client x.x.x.x 45882] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: style in /var/www/brewcompetitiononlineentry-master/includes/db/scores.db.php on line 3\n', referer: http://m.facebook.com
```
It looks like scores.db.php is loaded before styles is set.
I added the line
```
$style = "";
```
with the other variable initializations and the error is now gone.

**Comment by geoffhumphrey** [comment]
This error is being thrown because the variable $style is not needed (and thus defined) for the winner display by table method. It's only used by the by category and subcategory methods. Replacing lines 3 and 4 in /includes/db/scores.db.php with the following will stop the error:

```
if ($_SESSION['prefsWinnerMethod'] != 0) {	
	if ((isset($style)) && (is_numeric($style))) $style_pad = sprintf("%02d", $style);
	else $style_pad = $style;
}
```

This fix will be in place in the next commit and full version of 2.1.10.
