### ISSUE TITLE
Add Date/Time to .csv Exports

### ISSUE THREAD

**Issue by ercousin** [geoffhumphrey/brewcompetitiononlineentry#841]
After every competition I export all the entry/participant data so that I have it as a reference for future competitions.

We're currently 10 days out from our entry deadline, and I was going to check how many entries we had recieved by this date last year. Unfortunately the Entries_All_All report doesn't have a column for Date/Time and/or Last Modified.

Could you add this column to these types of reports?

**Comment by geoffhumphrey** [comment]
The Entries_All_All download dumps all data columns, including the brewUpdated column introduced a few versions ago (I'm not recalling when, but it's been at least since 2.1.0, I believe). Data in that column will tell you when that particular entry was updated.

By default, the name of the downloaded CSV file also appends the date it was generated in YYYY-MM-DD format. While it is possible to add a column to the download with the date/time the report was generated, I'm not sure it's necessary.

**Comment by ercousin** [comment]
I see it now! By default opening a csv in excel doesn't resize columns, so it was just showing up as #########

Thanks!

This can be closed, what I was asking for already exists :)
