### ISSUE TITLE
Some brewer names are missing.  Won't show their winning scores.

### ISSUE THREAD

**Issue by rpratt2479** [geoffhumphrey/brewcompetitiononlineentry#844]
Look at our winners page.  It omitted 2nd place in two tables and first place in one table.  http://momashin.brewcompetition.com/# Help me fix this.

**Comment by geoffhumphrey** [comment]
Hey @rpratt2479 - it looks like the missing entries on the results list are not assigned to a brewer. It's possible that an entrant's account that was associated with the entries was inadvertently deleted. Since this is a hosted account, please send along the names that are associated with entry numbers 23, 24, 54, and 76 and I'll update the DB directly.

**Comment by rpratt2479** [comment]
Entry 23:  Brad Wixom,  Belgian Tripel 26C.  2nd Place, Belgians
Entry 24:  Brad Wixom,  Wee Heavy 17C.  2nd Place, American and English Ales
Entry 54:  Dean Smith,  English Porter 13C.  1st Place, Porters and Stouts
Entry 76: Maciej Zawodniok, Strong Bitter 11C.  Did not place.

Thanks,

**Comment by geoffhumphrey** [comment]
OK, got things worked out and the list of winners is now complete on your installation's home page.

I'm investigating a cause, but it appears that the user account records for each of those you listed was deleted. Unfortunately, I wasn't able to restore them from a backup (the monthly backup was too old and the weekly and daily backups did not have the records), so I had to recreate the accounts with dummy data. The users and/or you will need to edit these accounts to update personal information such as addresses, phone numbers, club affiliations, AHA numbers, etc.

Apologies for the inconvenience.

**Comment by rpratt2479** [comment]
It looks great.  Thank You
