### ISSUE TITLE
Custom style entry form error

### ISSUE THREAD

**Issue by jodygrenert** [geoffhumphrey/brewcompetitiononlineentry#852]
Here's the site where I'm having a problem: www.obw.brewcomp.com,
I've added a custom style (35A. The Beast) and required a field asking entrant to enter ABV. 
When you try to add an entry in that category, the form gives you this error message:
 "More information is required for your entry to be accepted and confirmed. See the area(s) highlighted in RED below."

**Comment by foggdogg001** [comment]
I am also receiving this same error in trying to create a New England IPA category and want to specify session, standard or double strength. This is similar to an issue I reported back in 2015, issue #551. I used the Cider or Mead category as you suggested as a workaround but this causes issues when dealing with pull sheets, scoring and BOS because it puts those beers in the wrong style category. Please Help!

**Comment by geoffhumphrey** [comment]
After a hiatus for the holidays, I'm getting through previous issues. Apologies for the tardy reply. I'll take a look at the code and report back. In any case, I have confirmed that the custom style is added to the DB, but the requirements are not.

**Comment by geoffhumphrey** [comment]
The required info was not saving because the post variable was not populating. 

The hosted installations above have been fixed. For all others, changing the following lines from /includes/process/process_styles.inc.php will fix the issue:

Change:
```
$brewStyleEntry = $purifier->purify($brewStyleEntry);
$brewStyleInfo = $purifier->purify($brewStyleInfo);
```
To:
```
$brewStyleEntry = $purifier->purify($_POST['brewStyleEntry']);
$brewStyleInfo = $purifier->purify($_POST['brewStyleInfo']);
```

**Comment by foggdogg001** [comment]
Thank you for correcting this!

Cheers!
