### ISSUE TITLE
Assign tables prior to check in

### ISSUE THREAD

**Issue by donutbrew** [geoffhumphrey/brewcompetitiononlineentry#882]
It is useful to be able to organize entries for judging before they are received.

**Comment by julien-gibson** [comment]
I'd like to second this.  Our club runs some competitions as "quickies", where entry drop off and judging are all on the same day, but we close registration the previous day. If I could sort out the tables in that gap, it would make the judging day far simpler.

**Comment by MarsMug** [comment]
I will third this.  Many UK competitions will unpack entries 24hrs or less before judging.  There's simply not the time to organise all the entries and print pull sheets etc after unpacking.
For the competitions I've been involved with we mark everything as received, organise the tables on BCOEM.  

We get people thinking their bottles have arrived safely (or confused as they haven't sent them yet!).

**Comment by geoffhumphrey** [comment]
Current programming is predicated upon the logic that comp organizers do not want to have entries on pullsheets that are not physically present to save cellar people and/or stewards going on wild goose chases for non-existent entries (as an organizer myself, I can't imagine sorting entries and then attempting to judge them within 24 hours - I would be a freaking stressed out mess!).

To remove the restriction that an entry must be marked as "received" to be counted as eligible to be assigned to a table, some major programmatic adjustments are required in numerous SQL statements throughout the program to remove ```brewReceived='1'``` conditions. In the current version, there are 100+ instances across 24 files. I would encourage an installation on a separate test instance if you are wanting to tackle the task.

I'll put the suggestion in the queue for consideration in the 3.0 conversion planned for late next year.

**Comment by ercousin** [comment]
I agree that sorting and judging within 24 hrs would be super stressful. We
used to do that without incident for our 30-50 entry comps, but it would be
impossible for comps with 800 entries.

For Brew Slam we decide on (and announce) the award categories before we
even open entry registration (similar to NHC):
https://www.gtabrews.ca/wp-content/uploads/2019/11/Award-Categories-Brew-Slam-2019.pdf

I would love to be able to create Tables and assign Styles to Tables in
advance. Then whatever entries are registered will show up in the table
entry counts.

I think the distinction is that we assign "styles" to tables, rather than
"entries" to tables.

**Comment by MarsMug** [comment]
We've done it with competitions up to 550 entries.

The difficulty we have (at least in London) is the logistics - nobody has the personal space or time to receive all the entries, organise them and then move them to the judging location.

So we tend to get everything shipped to the venue, unpack and sort entries into their tables right there.  It takes several persons manpower, but it's doable.
Once we know the no-shows they can be crossed off the pre printed pull sheets, or otherwise let the head steward from a table do that.

It's not a show stopper issue, but it's an issue that I've seen in several competitions that run the same way.

**Comment by AdrienM76** [comment]
I'm going to add another use case:

Getting people to judge is difficult for us, no matter how far in advance we plan and communicate. (or how much we volunteer for their own competitions) Most local judges never even formally register or commit. We have to just hope they remember to show up, or surprise us and show up unannounced. There's no way we know of to 'enforce' anything better, they are volunteers after all.

One method we have found that works for 'enticement', is that many of our possible judges also want to enter the competition. Since they are traveling several hours to help us, we graciously allow them to bring their own entries rather than ship them early. If we insisted they ship, we'd likely lose both their entries and have less judges, and likely not enough judges to pull off the competition.

Being able to assign *entries* (not just styles) to flights and tables before they are received (because we reasonably expect them to arrive that day) would be very helpful and reduce the time spent with last minute organizing and printing the morning of the competition. (which is held up due to the late arrivals) We're managing without this, but the result is either marking them received without actually doing so and having to cross out stuff as previously mentioned, or being more stressed out that morning. Such a feature would alleviate both conditions and would be very welcome.

**Comment by geoffhumphrey** [comment]
See #1142 - there will be a “Tables Planning Mode” in the next release, 2.2.0.

**Comment by AdrienM76** [comment]
> See #1142 - there will be a “Tables Planning Mode” in the next release, 2.2.0.

Awesome! Thank You!

I understand 2.2.0 is not official. How 'unstable' is it? I could use it this weekend. (I don't mind being a bit of a guinea pig and can setup a separate instance in case I need to jump quickly back to 2.1.19)

**Comment by geoffhumphrey** [comment]
> I understand 2.2.0 is not official. How 'unstable' is it? I could use it this weekend. (I don't mind being a bit of a guinea pig and can setup a separate instance in case I need to jump quickly back to 2.1.19)

2.2.0 is 99% stable as of the latest commit earlier today - at least in my test environments. The goal is to release by 31 January.

**Comment by AdrienM76** [comment]
Thanks, that's good enough for me. (or Comp is on the 30th) I'll set up a test instance and try to copy my db over. I will definitely test out the Table Planning Mode and report back if I hit any snags.
