### ISSUE TITLE
Make judging numbers optional for barcode/QR code check-in

### ISSUE THREAD

**Issue by te4336** [geoffhumphrey/brewcompetitiononlineentry#884]
The judging numbers need to be optional for the Barcode/QR code check in process. The whole point of using a barcode scanner is to make the check-in process quicker and with larger comps where there are 600-2000 beers it's pointless when you have to go perusing through pages of judging labels to scan the correct one. This needs to be optional instead of a requirement to check entries in.

**Comment by geoffhumphrey** [comment]
Hi @te4336. I'm not sure which version you're running, but at least since 2.1.5, neither the QR code nor the barcode check-in functions have required any input in the judging number field. In the upcoming version, at least one entry number must be present when using the barcode check-in feature. In 2.1.5 through 2.1.11 not even that was required to process the form. 

In any case, for version 2.1.0 and up, if any form `<input>` field that has the _required_ attribute, simply removing that attribute will allow disable validation for that field.
