### ISSUE TITLE
2.1.9 -> 2.1.11: $setup_free_access, DBMS Overwrite?

### ISSUE THREAD

**Issue by mavandeh** [geoffhumphrey/brewcompetitiononlineentry#913]
Quite new to setting up databases, more of a question than an issue report.

Upgrading from 2.1.9 to 2.1.11 to fix the documented recaptcha issue I read about in a prior issue for a new user trying to register to submit entries.  Must I worry about losing entries and all my comp info I already have if I set `$setup_free_access =  TRUE;`?  Or will the DBMS just not let the script create tables that are already there?

Thanks!

**Comment by mavandeh** [comment]
Now that I've messed around with it, it seems to not be recognizing my email as an admin account anymore.  What's the best way to set up the admin account again?

**Comment by geoffhumphrey** [comment]
Hrm. That's odd. Not sure why your admin account would be missing. In any case, the most expedient way to set up the Admin account would be to drop all BCOE&M tables in your DB and go through the setup process again (due to the password encryption methodology utilized).

However, prior to doing that, go into your DB and take a look at the brewer and users tables. If you have a row in the users table with your admin credentials, take note of its id number. Then, check the brewer table and make sure there's a record in it with your info. If so, ensure that the uid is the same number of the id of your record in the user table. Both records must be present and relational for any user account to be fully recognized by the system.

**Comment by mavandeh** [comment]
Both entries exist.  I just pushed a fresh copy of the 2.1.9 files on top and all of a sudden it worked.

Must have been user error.  Thanks for your response!
