### ISSUE TITLE
error deleting old pdf files

### ISSUE THREAD

**Issue by huibertsp** [geoffhumphrey/brewcompetitiononlineentry#916]
for some reason after wiping my comp site there were still PDF files present. When I try to delete them I get an error: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'default WHERE id='default'' at line 1".

My worry is duplicate judging numbers and entrants getting scoresheets from last year that are not even the correct beer. How can I delete old pdf files?

site: http://scorpion.brewcompetition.com

**Comment by geoffhumphrey** [comment]
There are three ways you can delete scoresheets:
- Individually on the Admin Dashboard > Scoring > Scoresheets and Docs > Upload Multiple or Upload Single screen
- The Delete All Scoresheets button on the Admin Dashboard > Scoring > Scoresheets and Docs > Upload Multiple or Upload Single screen
-  The Admin Dashboard > Data Management > Purge > Uploaded Scoresheets link (v 2.1.12)

In 2.1.11 and prior, the Archive function did not purge or move the scoresheet files. In 2.1.12, when archiving, there will be an option to delete or move any uploaded scoresheets.

I've confirmed that the error you're reporting happens on when trying to delete individual scoresheets. I'll look into a solution.

In the meantime, the other two ways may be better for your environment since your installation is hosted. Simply getting rid of all uploaded scoresheets is recommended when resetting hosted installations for another competition cycle.

**Comment by Beakerboy** [comment]
The same error is presented when deleting a sponsor image:
http://[webroot]/includes/process.inc.php?action=delete&go=image&filter=[filename]&view=default

    You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'default WHERE id='default'' at line 1

The file IS removed successfully from the user_images directory despite the error.
