### ISSUE TITLE
brewer_entries display should not be lowercasing the filename!

### ISSUE THREAD

**Issue by mattoxb** [geoffhumphrey/brewcompetitiononlineentry#936]
In brewer_entries line 145 there's a line
`$scoresheet_file_name_judging = tolower($judging_number).".pdf"

This contradicts the documentation, which says that the filenames must match exactly.  Recommend removing `to_lower`, or else update the documentation to match the behavior.

**Comment by geoffhumphrey** [comment]
Since 2.1.10, for consistency, names and extensions of all files uploaded via the UI are converted to lower case upon upload. This, however, did not take into account admins who upload scoresheets to the user_docs directory directly via FTP.

I'll remove the strtolower function from the variable you mention above in both the brewer_entries.sec.php file and the entries.admin.php file. This way, scoresheets uploaded via FTP will also be recognized by the application and the download functions for users available.

I'll also update the documentation.
