### ISSUE TITLE
No notification is mcrypt is not installed

### ISSUE THREAD

**Issue by Beakerboy** [geoffhumphrey/brewcompetitiononlineentry#938]
We completed a competition using 2.1.12. After uploading scoresheets, the entries admin page would fail. The page was mostly white so the admin was not notified as to the source of the problem. Apache logs revealed it was because mcrypt was not installed. After adding the module, everything worked fine. It would be beneficial to have either have a warning on the screen, or a “site diagnostics”page that warns of incorrect permissions on files and directories, and missing libraries.

**Comment by geoffhumphrey** [comment]
Turns out mcrypt is deprecated for PHP 7.1, so we'll be using the [Open SSL library](http://php.net/manual/en/book.openssl.php) for this simple encryption use. 

Additionally, there will be checks for the required libraries/extensions utilized by the program and warnings built in to the install scripts and admin dashboard.

Of the top of my head, the following functions/extensions/libraries are utilized by the application.

- Enabled by default or integrated in the core:
  - FileInfo
  - Filesystem
  - Session Handling
  - Mail
  - Mcrypt (up through version 2.1.12 as primary, 2.1.13 as secondary)
- May need to be enabled (most webservers include this library):
  - OpenSSL (beginning with version 2.1.13)

I'll add more as I complete my review of the code.
