### ISSUE TITLE
Upgrade Failing from 2.1.9 to 2.1.10 (or higher)

### ISSUE THREAD

**Issue by spottybones** [geoffhumphrey/brewcompetitiononlineentry#947]
Hi,

I'm trying to upgrade a site from v2.1.9 to v2.1.10 and am finding I always redirected to the intitial setup pages after reloading the site after I change the webserver's document root to point to the directory I have the newer release installed in. I am prompted to set "$setup_free_access" to TRUE to do initial setup. When I did that as a test I then receive a duplicate primary key error.

The release notes for v2.1.10 indicate that a database update is not necessary when coming from v2.1.6 or later so I would expect it to just work.

**Comment by geoffhumphrey** [comment]
I am not able to recreate your issue in my test environments. Going from 2.1.9 to 2.1.10 or 2.1.11 should be seamless as you mentioned. I'm assuming you are upgrading the codebase but still using the same database.

Make sure your variables in the /site/config.php file are correct, especially `$database`, `$prefix`, and `$sub_directory` - any deviation in those may cause the setup script to run instead of any behind the scenes updates.
