### ISSUE TITLE
Entries won't delete

### ISSUE THREAD

**Issue by MASHManley** [geoffhumphrey/brewcompetitiononlineentry#951]
I'm using the little trash can icon trying to delete an entry. Message at the top of the window says "info deleted successfully". I check the list and it hasn't been deleted. I hit update at the bottom, still not deleted. Any ideas?

**Comment by geoffhumphrey** [comment]
I verified this when an Admin attempts to delete an entry from the Admin > Entries, Payments, and Participants screen. Users _are_ able to delete entries from their My Account screen. 

The work-around would be to have the user delete the entry (recommended) or to delete the user altogether, which will also delete their entries. Otherwise, if you can stand to ignore it, its presence in the entries list won't affect any further functions if it's not marked as paid and/or received.

A fix is in the latest master commit and will be in the next release.

**Comment by MASHManley** [comment]
Thanks, Geoff.

One of our participants is also saying they are receiving a warning that
the style they selected is not accepted. One is an IPA and one an APA, both
of which are allowed. We have other users that have registered them and
paid for them, so I'm not sure why this one guy is getting that warning.
Have you seen that before?

Thanks,

Paul

**Comment by geoffhumphrey** [comment]
Paul, that style issue is fixed now as well - see #950.
